### DISCUSSION TITLE
Cannot select custom content types when editing pages

### DISCUSSION THREAD

**Discussion by ianef** [bolt/core#1308] [General]
If a custom content type is added to a page definition, you cannot select any of the records.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | master
| Install type                   |  GitHub checkout
| PHP version                 | 7.3
| Web server                  | Apache

Reproduction
------------

Create a simple content type in contenttypes.yaml as follows:
```
testtype:
    name: Test Types
    singular_name: Test Type
    fields:
        caption:
            type: image
            label: Test Image
    show_on_dashboard: false
    show_in_menu: true
    default_status: published
    searchable: true
    icon_many: "fa:font"
    icon_one: "fa:font"
    order: [caption, id]
```
Create a few records for the new content type and then add the content type to the 'homepage' definition in contenttypes.yaml as follows:
```
        testimage:
            type: testtype
            label: Test Type

```
Now edit the homepage and scroll to the Test Type section, all you get is an edit box and no selection of the records that were previously created.
![content-type1](https://user-images.githubusercontent.com/5128087/79556451-01fe0e00-8099-11ea-9ae3-b7bdeb2f9683.png)

If you add a collection of the new content type:
```
        testimages:
            type: collection
            fields:
                testimage:
                    type: testtype
                    label: Test Type
```
You get the facility to add to the list but again, the list of content type records are not available, all you get a simple edit box.
![content-type2](https://user-images.githubusercontent.com/5128087/79556461-05919500-8099-11ea-94ac-5b7cbc6eddc5.png)

**Comment by technicallyerik** [comment]
You might be looking for [relationships](https://docs.bolt.cm/4.0/contenttypes/relationships).

```
homepage:
    relations:
        test-types:  #Note you want to use the slugified "name" here
            label: Select a Test Type
```

**Comment by ianef** [comment]
Hmmm... Well OK that works but it's not an obvious route to the content and in this case not very user friendly.

What was really nice about the content types on the Content tab was that it followed the flow of definitions. If these matched how the page template was laid out then it is really nice and easy for a non-technical user to work out the flow of the page from top to bottom when making edits.

Now we have chucked in another tab for them to look at that has no positional reference to the page layout.

There is no visual representation of media content in this case, just tags of file names which, for a lot of image files, may have zero to do with the content of the image, 20200119_150019.jpg for example.

Is there a way of templating the dropdowns to show a thumbnail? Also is there a way of getting the relationship onto the content tab in a position that relates to the page layout?

**Comment by ianef** [comment]
If I add collection of images to my page content type:
```
        images:
            type: collection
            fields:
                image:
                    type: image
                    extensions: [ jpg, png ]
```
I get a really nice form that allows me to add new images or select from existing ones:
![content-type4](https://user-images.githubusercontent.com/5128087/79593887-0398f780-80d4-11ea-8394-190289633c7f.png)

Do I have to add some template or view somewhere to do this with a custom content type?

**Comment by bobdenotter** [comment]
This is not correct: 

```yaml
        testimage:
            type: testtype
            label: Test Type
```

For the type, you can only use the actual existing types. One solution is what @technicallyerik mentioned, but a simple `type: select` should also work: https://docs.bolt.cm/4.0/fields/select#populating-the-values-from-a-contenttype

**Comment by ianef** [comment]
Many thanks @bobdenotter, using a select makes it possible but I still feel that being able to use a collection here would be a great advantage, it would make the UI an awful lot more intuitive if you could create your custom objects where you want to use them.

What about my previous comment 'Do I have to add some template or view somewhere to do this with a custom content type?'. I'd really like the collection type to show the correct form from a custom component type just like it does with an image.

```
        thisworks:
            type: collection
            fields:
                title:
                    type: image
        thisdoesnot:
            type: collection
            fields:
                title:
                    type: mycontenttype
```
Using the above you get a nice form when you use a image and the type and just a text box with the custom content type.
