### DISCUSSION TITLE
Add support for `filter: …`

### DISCUSSION THREAD

**Discussion by bobdenotter** [bolt/core#1794] [Ideas / Feature requests]
```yaml
somevalue:
   type: select
   values: pages/{title}
   filter: { categories: news }
```

In v3 we had a `filter: ` option for select fields. We should re-add that. 😇
