### DISCUSSION TITLE
Field collection bug

### DISCUSSION THREAD

**Discussion by myriaml** [bolt/core#2275] [Q&A]
Hi,
I have a collection field but the button for add thing on it is only available when the content is save?

Screen capture no save
![Nouveau-Objectif](https://user-images.githubusercontent.com/9095827/103392046-fd27a000-4ae9-11eb-9630-9d99c8743ee3.png)

Screen capture save
![Voyage](https://user-images.githubusercontent.com/9095827/103392047-fdc03680-4ae9-11eb-9b61-6a5c3c3bb008.png)

Why? 

Here my contenttype:
```
objectifs:
  name: Objectifs
  singular_name: Objectif
  fields:
    slug:
      type: slug
      uses: [nom]
    nom:
      type: text
      label: Nom
    description:
      type: redactor
      label: Description
    datemaximum:
      type: date
      label: Date maximum
    status:
      type: select
      values: [ En cours, Fin, Début ]  
    objectifs_repeater:
      type: collection
      label: Objectif
      fields:
        set: 
          type: set
          label: Objectif
          fields:
            objectif:
              type: redactor
              label: Objectif
            status:
              type: select
              values: [ En cours, Fin, Début ]
  relations:
    Journals anxieuse:
      multiple: false
      required: false
      label: Choisir un journal
      order: -id 
  listing_template: objectifs.twig
  listing_records: 30
  default_status: published
  order: -publishedAt
  records_per_page: 10
  icon_many: "fa:bullseye"
  icon_one: "fa:bullseye"
```

I use bolt 4.1.5. 

Thanks !

**Comment by bobdenotter** [comment]
Hi, @myriaml 

I've not been able to reproduce this yet.. For me it works as expected: 

![Schermafbeelding 2021-01-04 om 08 39 23](https://user-images.githubusercontent.com/1833361/103512094-74ea2780-4e68-11eb-9733-0cdc5b27589b.png)

(when I click "new", before saving)

Could try 'simplifying' it, and see if it works then? Hopefully we can then narrow down where it breaks. Try this, please:

```yaml
objectifs2:
  name: Objectifs2
  singular_name: Objectif2
  fields:
    slug:
      type: slug
      uses: [nom]
    nom:
      type: text
      label: Nom
    coll:
      type: collection
      label: Objectif
      fields:
        set: 
          type: set
          label: Objectif
          fields:
            objectif:
              type: redactor
              label: Objectif
            status:
              type: select
              values: [ En cours, Fin, Début ]
 ```
