### DISCUSSION TITLE
Using API in Bolt 4, how can I get the "related contenttype" fields?

### DISCUSSION THREAD

**Discussion by tourdefran** [bolt/core#2279] [Q&A] [answered]
Hello!
I'm using Bolt 4 API in order to build the backend, I need to use it as a headless because of the requirements of the project...
Nuxt on the Front End..

The thing is, I can't get the related contenttype's fields in an API call, any clue?
I want to get all the episodes related to one show, so I can list the content,
thanks in advance!

```
episodios:
    name: Episodios
    singular_name: Episodio
    fields:
        titulo:
            type: text
            class: large
            group: Entrada
        fecha:
            type: date
        tracklist:
            type: article
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
        imagen:
            type: image
            upload: entries
        mixcloudlink:
            type: text
            label: Link Mixcloud del episodio
            placeholder: 'https://www.mixcloud.com/NTSRadio/naafi-x-nts-radio-28th-february-2015/'
            postfix: "Link obtenido desde Mixcloud > share | Ejemplo: https://www.mixcloud.com/NTSRadio/naafi-x-nts-radio-28th-february-2015/"
            fixture_format: '{url}'
        slug:
            type: slug
            uses: titulo
            group: Meta
    relations:
        shows:
            multiple: false
            order: title
            label: Seleccionar un Show
            required: true
    taxonomy: [ categories, tags, groups ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: published
    order: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
```

```
shows:
    name: Shows
    singular_name: Show
    fields:
        titulo:
            type: text
            class: large
            group: Entry
        descripcion:
            type: textarea
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
        imagen:
            type: image
            upload: shows
        slug:
            type: slug
            uses: titulo
            group: Meta
    relations:
        people:
            multiple: false
            label: Autor de este Show
            required: true
        episodios:
            multiple: true
            label: prueba
            required: false            
    taxonomy: [ categories, tags, groups ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: published
    order: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
```
