### DISCUSSION TITLE
Redactor/HTML field - buttons settings for specific field?

### DISCUSSION THREAD

**Discussion by lexislav** [bolt/core#2572] [Q&A]
I know I can configure redactor field's buttons and plugins in config/extensions/bolt-redactor.yml.
Is possible to override this on single field somehow? Or create more configurations in bolt-redactor.yml file and then call them in field setup?

What I am trying to do:

```
news:
    fields:
        title:
            type: text

        # first redactor field for simple edits
        teaser:
            type: redactor
            settings:
                buttons: [ 'bold', 'italic', 'link' ]
                plugins: []

        #second redactor field with dafault settings from config file
        body:
            type: redactor
            buttons: [ bold, italic, format, lists, link, html, image ]
            plugins: [ fullscreen, table, inlinestyle, video, widget ]

```

Right now, only solution for this I am aware of is to configure other field type (html or markdown) for teaser field and redactor for body fields.
