### DISCUSSION TITLE
Where do image fields get thumbnail sizes from?

### DISCUSSION THREAD

**Discussion by andysh-uk** [bolt/core#3176] [Q&A] [answered]
Hi community,

I have a content type which has a plain image field like this:

```
lyrics_artists:
    ...
    fields:
        ...
        image:
            type: image
            label: Image
            group: Media
```

In my main `config.yaml`, thumbnails are configured as follows (this is the default config, I haven't changed this):

```
thumbnails:
    default_thumbnail: [ 320, 240 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    save_files: true
    allow_upscale: false
```

I then use the Bolt `Content` class to retrieve the image in a controller (this is an API that returns JSON-encoded values to the website front-end for use in Javascript):

```php
$image = $content->getFieldValue('image');
```

This returns an array (or might be an object) as follows (this is when it has been serialized as JSON);

```
"image":{
    "filename":"lyrics-artists\/2022\/03\/E83B5F3C-425D-4317-92E2-2681D2643688.jpeg",
    "path":"\/files\/lyrics-artists\/2022\/03\/E83B5F3C-425D-4317-92E2-2681D2643688.jpeg",
    "media":15,
    "thumbnail":"\/thumbs\/400\u00d7400\/lyrics-artists\/2022\/03\/E83B5F3C-425D-4317-92E2-2681D2643688.jpeg",
    "fieldname":"image",
    "alt":"",
    "url":"https:\/\/andysh.uk\/files\/lyrics-artists\/2022\/03\/E83B5F3C-425D-4317-92E2-2681D2643688.jpeg",
    "extension":"jpeg"
}
```

The thumbnail link is returned with a size of 400x400, without cropping, even though my thumbnail config says 320x240 and 1000x750 with cropping.

Where does this 400x400 come from?

I wondered if it can be configured on a per-field basis (which would be ideal) but I couldn't see anything in [the Image field's documentation](https://docs.boltcms.io/5.0/fields/image).
