### DISCUSSION TITLE
How multi languages ​​work

### DISCUSSION THREAD

**Discussion by AndreyChursin** [bolt/core#3447] [Q&A]
Hi! 
I try to migrate to Bolt from other CMS, and I have several questions about localization.
General component `{% include 'helpers/_languageselect.html.twig' %}` returns urls with '?_locale=en'
And this setting is not saved between pages and I see other localization only if I have '?_locale'  parameter....

Were I can find description for this case?
And how I should setup routes.yaml for "Filesystem based page" with several languages?
```
about:
  path: /{language}/about        # not work  
  defaults:
    _controller: Bolt\Controller\Frontend\TemplateController::template
    templateName: about.twig
```

And how it be correct in menu.yaml ?
```
footer:
  - label: About
    title: About us
    link: /{language}/about   # not work
```
