### DISCUSSION TITLE
How to set/show cross relations?

### DISCUSSION THREAD

**Discussion by AndreyChursin** [bolt/core#3517] [Q&A]
I have a list of courses on Bolt and I need add trainer for them
```
courses: 
  relations:
          trainers:
              ....
          
trainers:
      ....
      
```

But on the trainer's page I can't see all the courses in which it was used! 
should I add relation field for trainers and add all courses there(?):
```
trainers:
    relations:
        courses: 
        ....
```
