### ISSUE TITLE
error when trying to create a new block

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1048]
bolt 4rc2, php 7.2 

when I click 'new block', I get this error in two different installations (1 mysql, 1 sqlite):

![boltget](https://user-images.githubusercontent.com/21077532/74101579-97ca6980-4b3b-11ea-91e8-4f9db324c5be.png)

**Comment by bobdenotter** [comment]
I wonder if this is related to #1005 somehow. We couldn't reproduce that one either. 🤔 

@0spinboson How did you install this? Is it "fresh" or upgraded from earlier beta's?

**Comment by bobdenotter** [comment]
Dumb suggestion: Could you run `bin/console cache:clear` ?

**Comment by I-Valchev** [comment]
Hi @0spinboson, have you by any chance tried to set a default value to the image field in the blocks like so:

```
blocks:
        ...
        image:
            type: image
            default: "someimage.jpg"
        ...
```

If so, this is the reason why you're getting an exception. The proper way to set an image default would be:

```
blocks:
        ...
        image:
            type: image
            default:
                    filename: "someimage.jpg"
        ...
```

We'll be updating the documentation to reflect how default values work in Bolt 4. For the time being, you can refer to #1038.
