### ISSUE TITLE
Content-Type Relationships - Associated items not loading

### ISSUE THREAD

**Issue by wgaulke** [bolt/core#1081]
The `record.related()` does not load related content. 

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC 3
| Install type                   |  Composer install 
| PHP version                 | 7.3
| Web server                  | Apache / Nginx 

Reproduction
------------
I have a simple content type with a relation to another content type:

```
contents:
    name: My Content
    slug: contents
    singular_name: Content
    singular_slug: content
    fields:
       title:
            type: text
            label: "Titel"
            localize: true
            group: Content
       slug:
            type: slug
            uses: [title]
            group: Content
       text:
            type: html
            localize: true
            group: Details
    locales: ['de','en'] 
    relations:
        usecases:
            multiple: true
            label: "Select a use case"
            order: -id
```

Selection of single / multiple Use-Cases for the content is possible. Saving in the backend is successful.

### Expected result

I should be able to get related content using `{% set relatedusecases = record.related() %}` to put it into my template. 

### Actual result

`{% set relatedusecases = record.related() %}` returns null (relatedusecases is null, to be exact). 

### Wait, there is more

If I use the filter  `{{dump(record|related_values('usecases'))}} ` I am able to get an array of ids of the related content. However, no other of the `RelatedExtension.php` functions / filters seem to return the desired result.
