### ISSUE TITLE
Menu has incorrect links

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1116]
When making a menu like this: 

```yaml

main:
  - label: Home
    link: homepage
    class: homepage
  - label: About
    link: /page/about    
  - label: All packages
    link: /packages
  - label: The Bolt site
    link: https://boltcms.io
    class: bolt-site
```

The output is incorrect. The "About" should link to `/page/about`, but it has no link in the rendered HTML. 

<img width="691" alt="Screenshot 2020-02-23 at 19 24 19" src="https://user-images.githubusercontent.com/1833361/75117491-1d890180-5672-11ea-9442-ecd50cc29c52.png">
