### ISSUE TITLE
Errors in taxonomy listings

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1213]
I tried to make a listing of entries with a certain category. Like this:
`https://mysite.local/category/portfolio`
I am not sure if this is a bug or my own fault :)

This listing should show a number of entries with the category "portfolio" but I get the following error:

```
Argument 2 passed to Bolt\Repository\ContentRepository::findForTaxonomy() must be an instance of Tightenco\Collect\Support\Collection, null given, called in /Users/peterboorsma/Dropbox/Sites/isa/vendor/bolt/core/src/Controller/Frontend/TaxonomyController.php on line 47
```

From the log:

`CRITICAL                 17:42:17 | php | Uncaught Error: Argument 2 passed to  Bolt\Repository\ContentRepository::findForTaxonomy() must be an instance  of Tightenco\Collect\Support\Collection, null given, called in  /Users/peterboorsma/Dropbox/Sites/isa/vendor/bolt/core/src/Controller/Frontend/TaxonomyController.php  on line 47                                     {     "exception": {} }
-- | -- | --
CRITICAL                 17:42:17 | request | Uncaught PHP Exception TypeError: "Argument 2 passed to  Bolt\Repository\ContentRepository::findForTaxonomy() must be an instance  of Tightenco\Collect\Support\Collection, null given, called in  /Users/peterboorsma/Dropbox/Sites/isa/vendor/bolt/core/src/Controller/Frontend/TaxonomyController.php  on line 47" at  /Users/peterboorsma/Dropbox/Sites/isa/vendor/bolt/core/src/Repository/ContentRepository.php  line 39                                     {     "exception": {} }`

This is 'categories' in taxonomy.yaml:

```yaml
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options:
        portfolio: Portfolio
        d-d: D&D
        sketchbook: Sketchbook
        profilepaper: Profielwerkstuk
        fanart: Fan Art
        experiments: Experiments
```

And this is my template:

```twig
{% if taxonomy is defined %}
{{ __('general.phrase.overview-for', {'%slug%': taxonomy.options[slug]|default(slug) }) }}
{% endif %}

        {% for record in records %}
            <div>
                <h2><a href="{{ record|link }}">{{ record|title }}</a></h2>

                {% if record|image %}
                    <a href="{{ record|image }}">
                        <img src="{{ thumbnail(record, 400, 260) }}" alt="{{ (record|image).alt|default(record|title) }}">
                    </a>
                {% endif %}
            </div>
        {% else %}
            <div>
                <h2>{{ __('general.phrase.no-content-found') }}</h2>
                <p>
                    {{ __("Unfortunately, no content could be found. Try another page, or go to the <a href=\"%paths_root%\">homepage</a>.", {'%paths_root%': path('homepage')} ) }}
                </p>
            </div>
        {% endfor %}
```
