### ISSUE TITLE
Associating entry relations in content types using keys

### ISSUE THREAD

**Issue by technicallyerik** [bolt/core#1215]
I'm not sure if this is a bug or documentation related, but associating entries to a type don't quite work how I would expect.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0-rc.7
| Install type                   |  Composer install
| PHP version                 | 7.2.22
| Web server                  | Apache
| For UX/UI issues        | Safari 13.0.5

Reproduction
------------

### Specifics

I setup my contenttypes.yaml as follows:

```
extpost:
    name: "External Posts"
    singular_name: "External Post"
    ... (abridged)

blog:
    name: Blog
    singular_name: Blog
    relations:
        extpost:
            multiple: false
            label: Select an external post
            order: -id
    ... (abridged)
```

### Expected result

I would assign the relation using the key of the other content type.

### Actual result

When I attempt to create a new Blog content type in the UI, I get the following error:

> An exception has been thrown during the rendering of a template ("Tried to get content from ContentType 'extpost', but no ContentType by that name/slug exists.").

It turns out I need to use the following instead, where the key is the "singular name", lower cased, with spaces replaced by hyphens.

```
    relations:
        external-post:
            multiple: false
            label: Select an external post
            order: -id
```
