### ISSUE TITLE
Backend: Content added with prefix value shown inline

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1219]
I added a prefixed text to a field like this:

```
        myfield:
            type: html
            label: Openingstijden
            prefix: '<h2>Adresgegevens</h2>'
```
This is the result in my backend:

<img width="374" alt="Screenshot 2020-03-24 at 18 44 22" src="https://user-images.githubusercontent.com/2750653/77459457-0d467c80-6e00-11ea-8c73-4a86a817d713.png">

IMO this prefix is a block element. the label should be shown below my prefix content.

-----
Bolt 4.0.0 RC11
