### ISSUE TITLE
Unable to remove items in multiselect field

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1229]
If you fill a multiselect field and then empty it, it is impossible to completely empty the field. 
I see there is already an open issue about this (https://github.com/bolt/core/issues/1214) but I found another problem with this: Bolt does not save the emptied field correctly.
After removing items from the select field and saving the record, the removed items reappear.

I tested it with  a "select from a contenttype" field in a contenttype.

```
select_exhibit:
    type: select
    values: tentoonstellingen/{id},{title}
    autocomplete: true
    sort: title
    multiple: true
    sortable: true
```
I made a screencast of this behaviour:
https://www.dropbox.com/s/yxxhq58tdrxmofz/Screen%20Recording%202020-03-27%20at%2012.01.38.mp4?dl=0

-------

Bolt 4.0.0 RC11
