### ISSUE TITLE
Unnecessary table prefixing when multiple db connection defined

### ISSUE THREAD

**Issue by rixbeck** [bolt/core#1256]
In case when some has multiple database connections with different entity managers the actual table prefixer solution will prefix all configured database tables not just in default Bolt DB.
   
Details
-------
Bolt table prefix settings in `services.yml` is intended for prefixing Bolt's own tables to avoid collisions in case when default db may contains tables already for different purposes. Prefixing tables with Doctrine now goes by event listener `\Bolt\Doctrine\TablePrefix:loadClassMetadata()` which invoked on `loadClassMetadata` event. Unfortunately currently it is not checking the contextual entity class belongs to another entity manager than default, so tables in different databases will be also prefixed which leads wrong queries has been built.

In general it causes problems when some would like to use Bolt as a manager for contents for his SF based application that uses different DB connections.       

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 / 4.1 / master
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | unrelevant |

Reproduction
------------

I have the similar doctrine config like this:
```yaml
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_DRIVER): 'pdo_sqlite'
    env(DATABASE_URL): ''

doctrine:
# All your database connecctions used by the app should be defined here
    dbal:
        default_connection: default
        connections:
# Default Bolt Database connection
            default:
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL)%'
            
# Connection for a wireframe database which managed by a 3rd party application
            wireframe:
                driver:  pdo_mysql
# Connection url comes from env file doesn't necessary to describe here
                url: '%env(DATABASE_URL_WIREFRAME)%'
                charset: utf8
# Some of our tables has no primary fields needed to ORM so have to ignore them
# We are using non-standard db field types like ENUM so have to define how to cast a standard type if using reverse engineering mapping tables to entities
                mapping_types:
                    enum: string

# This is a db managed by our app, data here doesn't belongs either Bolt nor the 3rd party data 
            localdb:
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL_LOCALDB)%'

# ORM section
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            localdb:
                connection: localdb
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Oc:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Oc'
                        prefix: 'Oc\Entity\Oc'
                        alias: Oc

            wireframe:
                connection: wireframe
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Wireframe:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Wireframe'
                        prefix: 'Oc\Entity\Wireframe'
                        alias: Wireframe

            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                # auto_mapping: true
                mappings:
                    Bolt:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/vendor/bolt/core/src/Entity'
                        prefix: 'Bolt\Entity'
                        alias: Bolt
                dql:
                    string_functions:
                        JSON_EXTRACT: Bolt\Doctrine\Functions\JsonExtract
```
Have to mention Bolt prefix settings remains unchanged here in `services.yml`. _(Only relevant sections or lines listed here)_
```yaml
parameters:
    locale: 'en'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en|nl|es|fr|de|pl|it|hu|pt_BR|ja|nb|nn|nl_NL|nl_BE|is|ru
    app.notifications.email_sender: anonymous@example.com
    bolt.table_prefix: bolt_
    bolt.backend_url: /bolt
#...
services:
#...
    Bolt\Doctrine\TablePrefix:
        arguments: [ "%bolt.table_prefix%" ]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, lazy: true }
#...
```
Now the handler class
```php
<?php

declare(strict_types=1);

namespace Bolt\Doctrine;

use Bolt\Common\Str;
use Doctrine\ORM\Event\LoadClassMetadataEventArgs;
use Doctrine\ORM\Mapping\ClassMetadataInfo;

class TablePrefix
{
    private $tablePrefix;

    public function __construct(string $tablePrefix)
    {
        $this->tablePrefix = Str::ensureEndsWith($tablePrefix, '_');
    }

    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs): void
    {
        $classMetadata = $eventArgs->getClassMetadata();

        if (! $classMetadata->isInheritanceTypeSingleTable() || $classMetadata->getName() === $classMetadata->rootEntityName) {
            $classMetadata->setPrimaryTable([
                'name' => $this->tablePrefix . $classMetadata->getTableName(),
            ]);
        }

        foreach ($classMetadata->getAssociationMappings() as $fieldName => $mapping) {
            if ($mapping['type'] === ClassMetadataInfo::MANY_TO_MANY && $mapping['isOwningSide']) {
                $mappedTableName = $mapping['joinTable']['name'];
                $classMetadata->associationMappings[$fieldName]['joinTable']['name'] = $this->tablePrefix . $mappedTableName;
            }
        }
    }
}
```
### Reproducing
First I was trying to import entity from an existing database
`bin/console doctrine:mapping:import "Oc\Entity\Wireframe" --em wireframe annotation --path=src/Entity/Wirefrfame`
Even there is a bug in `knplabs/doctrine-behaviors (^2.0)` already fixed in its master branch but with patching I've got an entity class like this. _(only relevant lines...)_
```php
<?php

namespace Oc\Entity\Wireframe;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * Project collection for read
 *
 * @ApiResource(
 *     routePrefix="/wireframe",
 *     collectionOperations={"get"},
 *     itemOperations={
 *         "get"={
 *             "controller"=NotFoundAction::class,
 *             "read"=false,
 *             "output"=false,
 *         },
 *     },
 * )
 * @ORM\Entity(repositoryClass="Oc\Repository\Wireframe\ProjectRepository")
 * @ORM\Table(name="bolt_project", uniqueConstraints={@ORM\UniqueConstraint(name="source_system_id", columns={"source_system", "source_system_id"})}, indexes={@ORM\Index(name="regszam", columns={"regszam"}), @ORM\Index(name="telepules", columns={"telepules"}), @ORM\Index(name="megye", columns={"megye"}), @ORM\Index(name="korzet", columns={"korzet"})})
 * @ORM\Entity
 */
class Project
{
...
```   
In the `@ORM\Table(name="bolt_project", ...` shows our entity has been prefixed.

From the other hand this class later annotated by me to be an API endpoint and checking the result calling causes exceptions because the SQL string `FROM` object expanded to `bolt_project`, regardless the table entry manually edited to `@ORM\Table(name="project", ...`.

### Workaround

It is clear here we can omit prefixing in the listener if the entity class is not belongs to Bolt's default connection extending `Bolt\Doctrine\TablePrefix` like this

```php
<?php
namespace Oc\Doctrine;

use Doctrine\ORM\Event\LoadClassMetadataEventArgs;

class TablePrefix extends \Bolt\Doctrine\TablePrefix
{
    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs): void
    {
        /* It would be grerat to be able to decide on which EM used */
        // $em = $eventArgs->getEntityManager();
        /* But now just by class name... */
        $classMetadata = $eventArgs->getClassMetadata();
        if (strpos($classMetadata->getName(), "Bolt\\") === 0) {
            parent::loadClassMetadata($eventArgs);
        }
    }
}
```
...and in `services.yml` 
```yaml
services:
# ...
    Oc\Doctrine\TablePrefix:
        arguments: [ "%bolt.table_prefix%" ]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, lazy: true }
```

### Design considerations

I'm not sure what solution would be preferred therefore I didn't pushed a pull request. 
I think the globally configured prefix should be moved out to `doctrine.yml` under orm `entity_managers` section and prefixer would decide wether prefixing or not. 

I'm currently not sure is it possible to pass in that config any custom entry...
