### ISSUE TITLE
Cannot create custom content types when show_in_menu:false

### ISSUE THREAD

**Issue by ianfoulds** [bolt/core#1307]
When you set 'shown_in_menu: false' for a custom content type you cannot create new records.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | master
| Install type                   |  GitHub checkout
| PHP version                 | 7.3
| Web server                  | Apache

Reproduction
------------

Create a new content type in contenttypes.yaml as follows:
```
testtype:
    name: Test Types
    singular_name: Test Type
    fields:
        caption:
            type: text
            label: Caption
    show_on_dashboard: false
    show_in_menu: false
    default_status: published
    searchable: true
    icon_many: "fa:font"
    icon_one: "fa:font"
    order: [caption, id]
```
Clear the cache and then click on 'Other Content' -> 'Test Types'. The new content type list is shown and is empty. Clicking on 'Create new Test Type' does nothing.

If 'show_in_menu' is removed or set to true, the 'Test Type' option appears in the main menu and you can create new records as expected.
