### ISSUE TITLE
Default option for sets

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1355]
Should work as this:

```
author:
    type: set
    fields:
        name:
             type: text
        age:
             type: number
        photo:
             type: image
    default:
        name: "Some Name"
        age: 34
        photo:
             filename: "me.jpg"
             alt: "This is a nice animal"
```
