### ISSUE TITLE
Collection field data not displayed after saving.

### ISSUE THREAD

**Issue by JTNMW** [bolt/core#1390]
after updating to rc 19 from rc 16, (see issue #1389), collection field entires are not being displayed after saving record. 

Data entered in collection field inputs is being persisted to database, but is not being displayed at backend or frontend for the record.

| Relevant Bolt Version | bolt 4 rc 19
| Install type                   |  Composer install 
| BC Break                     | 
| PHP version                 | 7.4 |
| Web server                  | Apache 
| For UX/UI issues        | Browser name and version

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by I-Valchev** [comment]
@JTNMW as with the previous one, can you please share your content type definition? Is this happening only for data which already existed in the database before updating to rc 19, or when adding new collection field entries in rc 19?

**Comment by JTNMW** [comment]
@I-Valchev Below the contenttype definition. As with other issue, this is the only change made on a clean Composer project install and is using the default definition cut and paste from bolt 4 documentation. Collections field entries are not showing for data already existing in database, and for new collection field entries. No error is being thrown, only collection field entries not being shown Backend or frontend.

```
entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        image:
            type: image
            group: media
            upload: entries
        video:
            type: video
        features:
            type: collection
            fields:
                title:
                    type: text
                image:
                    type: image
                    extensions: [ gif, jpg, png ]
                content:
                    type: html
    relations:
        pages:
          multiple: false
          order: title
          label: Select a page
    taxonomy: [ categories, tags, groups ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: published
    order: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
```
