### ISSUE TITLE
Collections are not shown

### ISSUE THREAD

**Issue by milosa** [bolt/core#1438]
When I try to add something to a collection, the item I just added to the collection is not shown in the UI.
I don't get errors, Bolt says the record was saved successfully.

My contenttype looks like:

```
site_settings:
    name: Site settings
    singular_name: Site setting
    fields:
        title:
            type: text
            class: large
            group: content
            label: Title
        services:
            type: collection
            fields:
                service:
                    type: set
                    fields:
                        title:
                            type: text
                        description:
                            type: textarea
                        image:
                            type: image
                            alt: true
        header_images:
            label: Header foto's
            type: collection
            fields:
                header_image:
                    label: Header foto
                    type: set
                    fields:
                        image:
                            type: image
                            alt: true
                            upload: header
        slug:
            type: slug
            uses: title
            group: meta
    viewless: true
    taxonomy: [ categories, tags, foobars ]
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"
```

I checked the `bolt_field` table. The records to the collection that I try to add are added to the table, with the correct locale that I want. They are just not shown in the UI. 

The output of `{{ htmllang() }}` is also empty. So this might be related...
I have the locales in `services.yaml` and bolt's `config.yaml` set to `nl`.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | Bolt 4.0.0 RC 22
| Install type                   |  Composer install
| PHP version                 | 7.4.6
| Web server                  | symfony server
| Operating System       | Darwin - 19.5.0

**Comment by bobdenotter** [comment]
Hi @milosa, could you see if this works better in RC 22?

**Comment by milosa** [comment]
I just tried RC 23, but it still doesn't show the collection items.  This is what I see:

![Schermopname 2020-06-07 om 13 09 25](https://user-images.githubusercontent.com/2864243/83967349-cf1a0e80-a8c0-11ea-929f-39197ec54d7d.gif)

I checked the database again. The items are added to the translation table, with the correct locale (nl).

**Comment by milosa** [comment]
Okay... weird. 

I created a new project with `composer create-project bolt/project`
Updated it to RC23 and copied my content types over. Changed the locale to `nl`.

And now it works. 
So I guess it must have had something to do with the updates or something.

**Comment by bobdenotter** [comment]
@milosa I've looked into it some more.. On the site where it didn't work, did you have this, in your `services.yaml`? 

```yaml
    Bolt\Event\Listener\ContentFillListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    Bolt\Event\Listener\FieldFillListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }
```
