### ISSUE TITLE
Unexpected results where { value: '!1' }

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1446]
Unselecting records with the` '!' `returns unexpected results. The following query doesn't seem to work:
` {% setcontent records = 'mycontenttype' where { value: '!1' } printquery %}`

In my specific case:
Ignore records where the value of the checkbox `hideme` is `'1'`.
` {% setcontent records = 'schilderijen' where { hideme: '!1' } printquery %}`

No records returned.

```
Printquery output:
SELECT content FROM Bolt\Entity\Content content WHERE content.contentType = :ct0 AND content.status = :status_1 AND (content.id IN(SELECT content_3.id FROM Bolt\Entity\Content content_3 INNER JOIN content_3.fields fields_3 INNER JOIN fields_3.translations translations_3 WHERE JSON_EXTRACT(translations_3.value, '$[0]') <> :hideme_1 AND fields_3.name = :field_3)) ORDER BY content.publishedAt DESC

    ct0: schilderijen
    hideme_1: 1
    status_1: published
    field_3: hideme
```

---

Bolt 4.0.0 RC22

**Comment by bobdenotter** [comment]
Is this version of Bolt updated? For me it _does_ seem to work as expected. I did make some changes to how checkboxes are handled here, though: https://github.com/bolt/core/pull/1428

(This is only in RC 22 and up)

**Comment by peterboorsma** [comment]
I use RC22 + the locale fixes. I will do some more testing.

**Comment by bobdenotter** [comment]
For the record (haha, ba-dum-tsk) i did this: 

```twig
    {% setcontent records = 'dummies' where { hideme: '!1' } printquery %}

    {% for rec in records %}
    <li>{{ rec.id }}. {{ rec|title }}</li>
    {% endfor %}
```

And the dummies contenttype is nothing more than: 

```yaml
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title
        hideme:
            type: checkbox
    icon_many: "fa:viruses"
    icon_one: "fa:virus"
```
