### ISSUE TITLE
[RFC] URL field

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1472]
I don't know whether this can be easily implemented in core or it might be seen more as an external resource for Bolt 4, but it would be nice to have a URL field to link to sitewide public records .

In Bolt 3, the wysiwyg editor allows you to add links in the content to internal records by opening the Link widget and Broswer server to select the record you want to link to from a list.

![url-field](https://user-images.githubusercontent.com/6607455/84505400-f0fb0300-acbd-11ea-8533-f9ab5ce4d311.JPG)

It would be nice to have that functionality for a "URL field" to just select the record you want to link to besides of manually typing in the URL in the text field to populate the field, specially when using blocks that contain a button representation for instance (button label + link URL).

```
fields:
    contentblocks:
        type: block
        label: Inhoud
        group: Inhoud
        fields:
            contentsection:
                label: Content section
                fields:
                    content:
                        label: Content
                        type: html
                    button_link:
                        label: Button link
                        type: text
                    button_label:
                        label: Button text
                        type: text
```
