### ISSUE TITLE
Contenttypes field group text are always capitilized in edit page

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1473]
Group field text defined in the Contenttype definition is capitalized in the CMS edit page.

https://github.com/bolt/core/blob/26eabd4272f21af694eb6ac2682e2ab75a22461c/templates/content/_tabs.html.twig#L8

![Capitalized group tags](https://user-images.githubusercontent.com/6607455/84513717-23aaf880-acca-11ea-8889-5a09895fd2e5.JPG)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 24
| Install type                   |  Composer install `composer create-project bolt/project projectname`
| BC Break                     | yes/no
| PHP version                 | 7.2 
| Web server                  | Built-in

Reproduction
------------
- Add the following grouped fields to a contenttype definition in `contenttypes.yml`
```
fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
        vw_title:
            type: text
            group: Buy Volkwagen Polo
        mb_title:
            type: text
            group: Buy Mercedes Benz
```
- Go to Create/Edit page in the backend.
- Notice tabs are being capitalized. 

### Expected result
The text I literally give to the group option in `contenttypes.yml`

In this use case: 
- Buy Volkwagen Polo
- Buy Mercedes Benz

### Actual result
The capitalized text of the group option:

- Buy volkwagen polo
- Buy mercedes benz
