### ISSUE TITLE
Adding two collection items, only saves one, causes SQL error when deleting

### ISSUE THREAD

**Issue by milosa** [bolt/core#1514]
Contenttype:

```yaml
        site_images:
            label: Site foto's
            type: collection
            fields:
                header_image:
                    label: Site foto
                    type: set
                    fields:
                        image:
                            type: image
                            alt: true
                            upload: images
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4 RC25
| Install type                   |  Composer install
| PHP version                 | 7.4.7 |
| Web server                  | symfony
| Database                     | sqllite 

Reproduction
------------
Start with empty content type.

Then add one image to the collection. But don't save the contenttype content.
Add another item (with image) to the collection.

Now click save.

**Problem 1**: Only the first image is displayed in the collection. The second collection item is displayed, but it is empty. (No image)

**Problem 2**: Hit `remove item` on the empty collection item, then clicking save, causes this SQL error:

```
php.CRITICAL: Error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: bolt_field.content_id in (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127 Stack trace: 
#0 (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(127): PDOStatement->execute(NULL) 
#1 (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL) 
#2 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(286): Doctrine\DBAL\Statement->execute() 
#3 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() 
#4 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php( {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: bolt_field.content_id in (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127\nStack trace:\n
#0 (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(127): PDOStatement->execute(NULL)\n
#1 (...)/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\\DBAL\\Driver\\PDOStatement->execute(NULL)\n
#2 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(286): Doctrine\\DBAL\\Statement->execute()\n
#3 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->executeInserts()\n
#4 (...)/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php( at (...)/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88)"} []

```
