### ISSUE TITLE
'Variable "user" does not exist' with Date Fields inside Collection

### ISSUE THREAD

**Issue by benplummer** [bolt/core#1515]
When using Date fields within a Collection field, the following RuntimeError takes place in the Admin Panel:

```Variable "user" does not exist.```

The line causing the error is `vendor/bolt/core/templates/_partials/fields/date.html.twig (line 33)`

My field definition is:

```
        price_list:
            type: collection
            fields:
                start_date:
                    type: date
                    label: Start Date
                    required: true
                end_date:
                    type: date
                    label: End Date
                    required: true
                price:
                    type: text
                    required: true
```

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0-rc.25
| Install type                   | Composer install
| PHP version                 | 7.3.17
