### ISSUE TITLE
Collection of Set Fields Not Displaying 

### ISSUE THREAD

**Issue by benplummer** [bolt/core#1540]
I have the following content type:

```
apartments:
    name: Apartments
    singular_name: Apartment
    fields:
        title:
            type: text
            required: true
        slug:
            type: slug
            uses: title
        short_description:
            type: text
            label: Short Description
            required: true
        long_description:
            type: textarea
            label: Long Description
            required: true
        price_list:
            type: collection
            label: Price List
            fields:
                price_list_item:
                    type: set
                    label: Price List Item
                    required: true
                    fields:
                        date_range:
                            type: text
                            label: Date Range
                            required: true
                        price:
                            type: text
                            required: true
            required: true
        additional_pricing_info:
            type: text
            label: Additional Pricing Information
        images:
            type: imagelist
            required: true
    listing_template: apartments.twig
    record_template: apartment.twig
    listing_records: 10
    icon_many: "fa:building"
    icon_one: "fa:building"
```

When I add `price_list_item`s in the Bolt Admin Panel, they are being saved to the database but they are not displaying on the `Apartment` edit page on the form or on the front-end when looping through to output them.

I've spoken with @I-Valchev and the code worked fine for him so it's possible this could be a niche issue but I'm struggling to see how I can get around it.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0.0 RC 25
| Install type                   |  Composer install
| PHP version                 | 7.3.17
