### ISSUE TITLE
HTML field not parsed when inside set/collection

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1558]
The HTML field is not parsed when inside a set or collection.

Also, if the name of the field is `content`, then `{{ setfield.content }}` returns the Content object, not the field.

**Comment by I-Valchev** [comment]
Can't seem to replicate it now... I'll try from home where it originally happened

**Comment by ymarkus** [comment]
@I-Valchev I've managed to replicate this issue. Here's an example of it not working:

`index.twig`:
```
<div class="carousel-inner">
    {% for image in record.slideshow %}
      <div class="carousel-item {%- if loop.first %} active{% endif %}">
        <img src="{{ image.imgfile.path }}" class="d-block w-100" alt="slideshow{{ loop.index }}">
        {% if image.imgcaption != "" %}
          <div class="carousel-caption d-none d-md-block text-dark mb-4 rounded">
            {{ image.imgcaption }}
          </div>
        {% endif %}
      </div>
    {% endfor %}
  </div>
```

`contenttypes.yaml`:
```
slideshow:
      type: collection
      fields:
        image:
          type: set
          fields:
            imgfile:
              type: image
            imgcaption:
              type: html
              placeholder: This is the field that reproduces the bug.
```

The HTML I entered: `<h1>HTML</h1><p>Test<br></p>`
The HTML that is returned: `&lt;h3&gt;Hi&lt;/h3&gt;`
