### ISSUE TITLE
Taxonomy name is slugified

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1587]
If I set a taxonomy to, e.g.

```yaml
tags:
    slug: knowledgebase /tags
    singular_slug: knowledgebase/tag
    behaves_like: categories
    multiple: true
    options: [ product management, process, design, code and tools, tutorials and learning]
```

Then, the name of the `product management` and `tutorials and learning` taxonomies are: `Product-management` and `Tutorials-and-learning`, but they should not contain `-`
