### ISSUE TITLE
[RFC] Allow set of height for textarea field

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#1663]
I don't know if this is to be supported in Bolt 4, but maybe it could be kept in as well.

In older versions of Bolt it was possible to set the minimum height of the textarea field by using the height option(see following example)

```        
sub_title:
    type: textarea
    label: Ondertitel
    height: 150px
```
