### ISSUE TITLE
Exception for entries after updating RC18 - RC33

### ISSUE THREAD

**Issue by wgaulke** [bolt/core#1684]
Argument 1 passed to Bolt\Utils\ContentHelper::isSuitable() must be an instance of Bolt\Entity\Content

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC33
| Install type                   |  Composer install
| PHP version                 | 7.4 |
| Web server                  | Apache / Nginx 

Reproduction
------------

We updated a old RC Install to the latest RC. We did it the follwing way:

* Create new RC33 Install with composer
* Copy Website Template and Contenttypes to new install
* Run bin/console doctrine:schema:update --force 
* Backend shows no more entries (but the paginator)
* Fronend crashes, if entries are listed

Our entry content-type:

```
entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        content:
            type: html
            height: 300px
        sliderimage:
            type: image
            group: media
        image:
            type: image
            group: media
            upload: entries
        imagelist:
            label: "Gallery"
            type: imagelist
        video:
            type: video
    taxonomy: [ categories, tags, groups ]
    relations:
        businessareas:
            multiple: false
            label: "Wähle eine Business Area"
            order: -id
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: draft
    sort: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
```

### Expected result

Backend and frontend should show all entries.

### Actual result

No entries are shown in the backend. 

Exception in frontend:
`Argument 1 passed to Bolt\Utils\ContentHelper::isSuitable() must be an instance of Bolt\Entity\Content, null given`

### Note

All other content types work. However, for all other content-types we use locales. For entries not.
