### ISSUE TITLE
Link target in html field 

### ISSUE THREAD

**Issue by kutulus** [bolt/core#1690]
Hi,

The link attribute "target" in an HTML field is currently not rendered.
- Bolt 4 RC33

contenttype.yaml:
```
...
        teaser:
            type: html
            height: 150px
            localize: true
```

config.yaml:
```
htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dt, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption, sub, super, figure, figcaption ]
    allowed_attributes: [ id, class, style, name, value, href, src, sizes, srcset, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]
```

Sourceview of html-Field:
`<p>Hier ein <a href="http://bla.com" title="Linktitel" target="_blank">Teaseer</a>...<br></p>`

Greetings
Stefano
