### ISSUE TITLE
related.link shows wrong url

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1700]
To get related records I use the code provided in [the docs](https://docs.bolt.cm/4.0/contenttypes/relationships#relations-in-templates):

```
    {% set relatedrecords = record|related %}
    {% if relatedrecords is not empty %}
        <p>Related content:</p>
        <ul>
        {% for related in relatedrecords %}
            <li><a href="{{ related.link }}">{{ related.title }}</a></li>
        {%  endfor %}
        </ul>
    {% endif %}

```

`{{ related.link }}` shows the url of the current record instead of the related item.

---
Bolt 4.0.0 RC34

**Comment by I-Valchev** [comment]
@peterboorsma 

It should be `{{ related|link }}`

Docs are out of date.. will update!

**Comment by peterboorsma** [comment]
Check. {{ related|link }} works. Should have seen that myself.

Is there a way to get related records from a specific contenttype?

In Bolt 3 this was the syntax:
`{% set relatedrecords = record.related('songs') %}`

Plus...
You could order the results by fieldname, like this:
`{% for related in relatedrecords|order('tracknumber') %}`

**Comment by I-Valchev** [comment]
@peterboorsma 

Yes, you can use `record|related('type')`

**Comment by peterboorsma** [comment]
@I-Valchev I... don't think so. When I do that, it returns (in my case) an empty array.

**Comment by I-Valchev** [comment]
Right, do you access it from the side where you define the relation, or from the receiving side?

**Comment by peterboorsma** [comment]
My contenttypes:
```

releases:
    name: Releases
    singular_name: Release
    fields:
        <<: *_defaults_titles

songs:
    name: Songs
    singular_name: Song
    fields:
        title:
            type: text
        tracknumber:
            type: number
            mode: integer
        slug:
            type: slug
            uses: title
    relations:
        releases:
            multiple: true
            required: false
            label: Select a related Release
            order: -id
```

On a **release page** I collect the related songs, like this:

```
			    {% set relatedrecords = record|related %}
			    {% if relatedrecords is not empty %}
			        <h3>Tracklisting</h3>

			        <ul>
			        {% for related in relatedrecords|order('tracknumber') %}
			            <li>
			            	<a href="{{ related|link }}">
			            		<span class="tracknumber">{{ related.tracknumber }}</span>
			            		<span class="title">{{ related|title }}</span><br>
			            	</a>
			        	</li>
			        {%  endfor %}
			        </ul>
			    {% endif %}
```
`{% set relatedrecords = record|related %}`
That works (returns my 2 related records)

`{% set relatedrecords = record|related('songs') %}`
Returns an empty array
