### ISSUE TITLE
error while creating a new entry in RC34 related to template selection

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1712]
with: 

```yaml
blocks:
    name: Blocks
    singular_name: Block
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: html
            height: 150px
        contentlink:
            type: text
            label: Link
            placeholder: 'contenttype/slug or http://example.org/'
            postfix: "Links This could either be an 'internal' link like <tt>page/about</tt>, if you use a contenttype/slug combination. Otherwise use a proper URL, like `http://example.org`."
        image:
            type: image
            attrib: title
            extensions: [ gif, jpg, png ]
        template:
            type: templateselect
    show_on_dashboard: true
    viewless: false
    default_status: publish
    searchable: false
    icon_many: "fa:cubes"
    icon_one: "fa:cube"
```

I get this error when I create a new record Record is created properly, but it doesn't assign a template. Existing records work fine, and can be edited.

![templateselecterror](https://user-images.githubusercontent.com/21077532/90120988-b401ca00-dd5b-11ea-9176-2e9afc5977e7.png)
