### ISSUE TITLE
save bug after changing field type to redactor and then back to html

### ISSUE THREAD

**Issue by 0spinboson** [bolt/core#1713]
rc34, bolt/redactor installed
added 'redactor' to the _fields and _field_blocks twig files in vendor/core
changed contenttype to this: 

```yaml
blogposts:
    name: Posts
    slug: blog-posts
    singular_name: Post
    singular_slug: blog
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
        slug:
            type: slug
            uses: title
            localize: true
        embedded:
            type: embed
            default:
                url: ""
                width: "480"
                height: "280"          
        image:
            type: image
        teaser:
          type: html
          localize: true
        body:
            type: html
            localize: true
        junked:
            type: html
            height: 100px
    taxonomy: [ categories, groups, tags ]
    listing_template: listing.twig
    locales: ['en','nl']
    viewless: false
    record_template: record.twig
    recordsperpage: 20
```

When I try to create a new post after changing the field type to redactor and then back to html, I get this error, which never goes away again: 

![Screenshot_2020-08-13_13-01-03](https://user-images.githubusercontent.com/21077532/90127266-33e06200-dd65-11ea-8a2e-d9e9d09214e1.png)
