### ISSUE TITLE
Listing pages filter by fields using query params

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#1719]
Example contenttype:
```
pages:
  singular_name: page
  name: pages
  fields:
    title:
      type: text
    category:
       type: select
       values: [ one, two, three ] 
```

Then:
The `/pages/?q=category=two` will return the listing `records` only containing the category `two`.

Essentially, automating `setcontent` used with query params to filter on field values.
