### ISSUE TITLE
Adding Relations returns exception error

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1724]
Adding a relation to a record returns an error when trying to save a record:
```
- [ ] An exception occurred while executing 'INSERT INTO bolt_relation (position, from_content_id, to_content_id) VALUES (?, ?, ?)' with params [0, 46, 2]:
- [ ] 
- [ ] SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
```

The relations field in my contenttypes.yaml:

```
    relations:
        releases:
            multiple: true
            required: false
            label: Select a related Release
            order: -id
```

This issue occurs after updating from RC33 > RC35

Maybe it has something to do with this fix:
https://github.com/bolt/core/commit/53b54a92a83cb72651652884e5193d800e076db9#diff-1a2603f0653b9e672ac2e898e20f1f04

---
Bolt 4.0.0 RC35
