### ISSUE TITLE
required: true does not work properly with date fields.

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#1743]
When adding the required: true option to a date field causes Bolt to behave unexpectedly. The date editor keeps popping up when trying to save the record.
See [this screencast](https://www.dropbox.com/s/wrgr1r3ln2e6j3b/Screen%20Recording%202020-08-20%20at%2017.49.41.mov?dl=0) for an example: 

My contenttype:

```
        date_to:
            type: date
            default: "first day of this month"
            required: true
```

---
Bolt 4.0.0. RC35
