### ISSUE TITLE
Slug sometimes not slugging

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1785]
Sometimes (I've seen it twice, and also reported by @peterboorsma), the slug doesn't generate. 

For the same site, my local setup works: 

![Screenshot_2020-08-27_at_08_18_02](https://user-images.githubusercontent.com/1833361/91399367-271c3d80-e83e-11ea-9414-678adc4133e5.png)

But on production it doesn't work: 

![Screenshot_2020-08-27_at_08_18_18](https://user-images.githubusercontent.com/1833361/91399434-44510c00-e83e-11ea-9597-0cb48bef783a.png)

The contenttype is pretty straightforward: 

```yaml
news:
    name: News
    singular_name: Newsitem
    recordsperpage: 5
    fields:
	title:
            type: text
            class: large
        image:
            type: image
        content:
            type: redactor
       	slug:
            type: slug
            uses: title
```

Could this be related to issue #1784, not detecting that "title" is indeed a valid field to generate the Slug from? 🤔
