### ISSUE TITLE
Add support for `filter: …`

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1794]
```yaml
somevalue:
   type: select
   values: pages/{title}
   filter: { categories: news }
```

In v3 we had a `filter: ` option for select fields. We should re-add that. 😇
