### ISSUE TITLE
Collection/Set 'move up' and 'move down' buttons behave erratically

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1818]
It seems like the Move up and Move down buttons jump 2 elements, instead of 1 by 1

Demo:
![screencast 2020-09-02 14-02-34](https://user-images.githubusercontent.com/1833020/92036729-88a04880-ed25-11ea-8be2-a43649be8ee3.gif)

**Bolt 4 RC 41**

**Comment by I-Valchev** [comment]
hi @eduardomart ,

Great gif, thanks a lot it really helps in seeing what the problem is.

I cannot reproduce this yet. Can you provide your contenttype? Did you save the new collection fields, or did you add them dynamically with the add button (but not yet saved)?

Thanks.

**Comment by eduardomart** [comment]
The collection fields were added and saved, and this is inside a singleton, this still havens after reopening the singleton

Here's the content type defs:

```
settings:
    name: Settings
    singular_name: Settings
    show_on_dashboard: false
    singleton: true
    viewless: true
    fields:
        carousel:
            type: collection
            group: Carousel
            fields:
                slide:
                    type: set
                    label: Slide
                    fields:
                        title:
                            type: text
                        image:
                            type: image
                            upload: carousel
        social:
            type: collection
            label: Social Media Networks
            group: Social Media
            fields:
                network:
                    type: set
                    fields:
                        name:
                            type: text
                            variant: inline
                        url:
                            type: text
                            label: URL
                            # pattern: url
                            variant: inline
                        icon:
                            type: image
                            label: Icon
                            extensions: svg
                            upload: social_icons
        paypal_success:
            type: redactor
            label: Success message
            postfix: |
                This message is displayed after a successful Paypal transaction is completed
                <hr>
            group: Paypal
        paypal:
            type: textarea
            label: Paypal button code
            height: 10
        instructions:
            type: hidden
    icon_many: "fa:cogs"
```

**Comment by I-Valchev** [comment]
I've worked with collections quite a bit in the last few days in relation to #1830 , but never once did I experience this 🙈

Right now I'm not quite sure how to reproduce it, lets label it a bug and see if it can be reproduced.

**Comment by eduardomart** [comment]
hi @I-Valchev 
I think I have found out what triggers the issue, it seems to be when we have more than one `collection` in the same content type, earlier I shared only the `collection` that was showing the issue (as you saw in the GIF), but now I am gonna share the full content type so that you can replicate it, I only noticed it because I moved one of the collections to its own singleton and then the other one was working as expected.

```
settings:
    name: Settings
    singular_name: Settings
    show_on_dashboard: false
    singleton: true
    viewless: true
    fields:
        carousel:
            type: collection
            group: Carousel
            fields:
                slide:
                    type: set
                    label: Slide
                    icon: "fa-image"
                    fields:
                        title:
                            type: text
                            variant: inline
                        image:
                            type: image
                            upload: carousel
                            variant: inline
        social:
            type: collection
            label: Social Media Networks
            group: Social Media
            fields:
                network:
                    type: set
                    fields:
                        name:
                            type: text
                            variant: inline
                        url:
                            type: text
                            label: URL
                            # pattern: url
                            variant: inline
                        icon:
                            type: image
                            label: Icon
                            extensions: svg
                            upload: social_icons
        paypal_success:
            type: redactor
            label: Success message
            group: Paypal
        paypal:
            type: textarea
            label: Paypal button code
            height: 10
```
