### ISSUE TITLE
text field's patterns (url and email) are never matched

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1819]
```
myfield:
   type: text
   pattern: url 
  # pattern: email <-- also doesn't work
```

Both [patterns](https://docs.bolt.cm/4.0/fields/common#required-and-patterns) `url` or `email` are not working, when used the pattern is never matched

Example:
<img width="733" alt="Screen Shot 2020-09-02 at 4 55 18 PM" src="https://user-images.githubusercontent.com/1833020/92049683-f0fc2380-ed3f-11ea-96c8-41bb0b962874.png">

However it does seem that regular expressions work
