### ISSUE TITLE
allow_numeric_slugs option [feature request]

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#1877]
Could we please have the `allow_numeric_slugs` like in v3?

Example:
I have a content type "Annual Festivals" with these definitions:

```
singular_slug: annual-festival
fields: 
    year: 
        type: text
   slug:
      uses: year
```

But I keep getting a slug generated like this: `/annual-festival/annual-festival-2018` which seems repetitive, I'd prefer to have a  clean/simple slug like: `/annual-festival/2018` which is why the `allow_numeric_slugs` option was so useful.
