### ISSUE TITLE
Translation problem with the "set" field type

### ISSUE THREAD

**Issue by brangabriel** [bolt/core#1934]
The `type: set` field doesn't show the translation for the selected language.

Details
-------

I checked the database and _the translation is actually saved_ for English and French, but somehow **only the English translation appears**.
Tested on a local server and on a staging server with the same result.

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | Bolt version 4.0.1
| Install type                   | Composer install 
| BC Break                     | no
| PHP version                 | 7.2
| Web server                  | Apache 
| For UX/UI issues        | Firefox 81.0 64bit

Reproduction
------------
![bolt4_translation](https://user-images.githubusercontent.com/7954200/94928872-f9758480-04cc-11eb-98f7-4223783344b1.gif)

ectract from the `contenttypes.yaml` file:

```yaml
forms:
    name: Forms
    singular_name: Form
    fields:
        title:
            type: text
            class: large
            label: Title of this Form
            localize: true
            group: Form
        content:
            type: collection
            fields:
                contentsetinput:
                    type: set
                    label: Input
                    fields:
                        label:
                            label: Label
                            type: text
                            variant: inline
                            localize: true
                        placeholder:
                            label: Placeholder
                            type: text
                            variant: inline
                            localize: true
                        icon:
                            label: Icon
                            type: text
                            variant: inline
                            placeholder: "fa-user"
                contentsetemail:
                    type: set
                    label: Email
                    fields:
                        label:
                            label: Label
                            type: text
                            variant: inline
                            localize: true
                        placeholder:
                            label: Placeholder
                            type: text
                            variant: inline
                            localize: true
                        icon:
                            label: Icon
                            type: text
                            variant: inline
                            placeholder: "fa-envelope"
                contentsetdropdown:
                    type: set
                    label: Dropdown
                    fields:
                        label:
                            label: Label
                            type: text
                            variant: inline
                            localize: true
                        options:
                            label: Options
                            type: text
                            variant: inline
                            placeholder: "Option 1, Option 2, Option 3"
                            localize: true
                contentsetradio:
                    type: set
                    label: Radio
                    fields:
                        label:
                            label: Label
                            type: text
                            variant: inline
                            localize: true
                        placeholder:
                            label: Inputs
                            type: text
                            placeholder: "Option 1, Option 2, Option 3"
                            variant: inline
                            localize: true
                contentsettextarea:
                    type: set
                    label: Textarea
                    fields:
                        label:
                            label: Label
                            type: text
                            variant: inline
                            localize: true
                        placeholder:
                            label: Placeholder
                            type: text
                            variant: inline
                            localize: true
        submit:
            type: text
            label: Submit button
            variant: inline
            localize: true
        slug:
            type: slug
            localize: true
            uses: [ title ]
            group: Meta
    show_on_dashboard: false
    viewless: true
    locales: ['en', 'fr', 'de']
    default_status: published
    searchable: false
    order: title
    icon_many: "fa:address-book"
    icon_one: "fa:address-book"
```

### Expected result

The field to be translated into the French (selected language)

### Actual result

The English (default language) is used instead of translating the field into French (selected language)

**Comment by bobdenotter** [comment]
@I-Valchev Do you know if this is a bug or a quirk?

**Comment by I-Valchev** [comment]
Hi @brangabriel , the definition is how the localization _should_ work. But you are right that it does not.

To allow you to keep working on your project, you can set `localize: true` to the collection itself and it will work.

**Comment by brangabriel** [comment]
Thank you @I-Valchev ; it works.

**Comment by denis-gorin** [comment]
And I'll put my two cents in as well.
I set `localize: true` for the `set` type too (`contentsetinput` in the example)

``` yaml

 content:
    type: collection
    localize: true
    fields:
        contentsetinput:
            type: set
            localize: true
            fields:
                label:
                    type: text
                    localize: true

```
