### ISSUE TITLE
Field type: file not uploading files

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#2000]
CT field definition:

```
book:
            type: file
            extensions: [ pdf ]
            upload: 'booklets'
            variant: inline
```

Produces this error every time:
<img width="645" alt="Screen Shot 2020-10-14 at 1 59 14 PM" src="https://user-images.githubusercontent.com/1833020/96044728-c1a00280-0e25-11eb-86e3-b91915c4298c.png">

The folder 'booklets' is successfully created, but file not uploaded.

Bolt 4.1
