### ISSUE TITLE
Reserved field name for fields within a Set

### ISSUE THREAD

**Issue by develth** [bolt/core#2013]
Hi,

when using the field name `name` in a set and want to output it via 'record.name', it just outputs the set name.

But Documentation just talks about `content`:

>Note, do not name fields inside a set with the name content. This is a reserved word for Bolt, because it is used to get a Record from it's field {{ myfield.content }}. You will not be able to access the field with name content inside a set.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1
| Install type                   |  Composer install
| BC Break                     | no
| PHP version                 | 7.4 
| Web server                  | Nginx

Reproduction
------------
### Specifics

Add Content-Type field:

```
copyright:
  type: set
  label: 'Copyright owner'
  fields:
    name:
      type: text
      label: Name
    website:
      type: text
      label: Webseite
      pattern: url
```

### Steps to reproduce

Output in File:

`
{{record.copyright.name}}
`

### Expected result

Given Input in Backend

### Actual result

The Field-Name of the set: `copyright`
