### ISSUE TITLE
Taxonomy singular_slug is being ignored when generating URL

### ISSUE THREAD

**Issue by andysh-uk** [bolt/core#2036]
I'm migrating [my existing WordPress website](https://andysh.uk) to be built in Bolt, so I'd like to maintain the URLs where possible.

One particular example is a category link - it should be `/category/software-development`, for example, but Bolt is generating it as `/categories/software-development`.

The taxonomy option `singular_slug` appears to be ignored - the `slug` is used when generating the URL using `link`.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1.2
| Install type                   |  Composer install
| BC Break                     | not sure
| PHP version                 | 7.4 |
| Web server                  | Nginx
| For UX/UI issues        | Firefox 81.0.2

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Using the default Bolt taxonomies set up with a new Bolt 4.1.2 site, categories and tags, the `singular_slug` option appears to be ignored when the URL is generated using the `link` Twig filter.

### Specifics

Using the default Bolt taxonomy for "categories":

```
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options:
        - "Something"
        - "Something else"
    required: false
```

You can see the `singular_slug` is set to `category`, while the `slug` is set to `categories`.

However the link generated is /categories/something, instead of /category/something.

Twig template:

```
{% setcontent blog_posts = 'blog' orderby '-publishedAt' %}
{% for blog_post in blog_posts %}
    {% if blog_post|taxonomies['categories'] is defined %}
        {% for category in blog_post|taxonomies['categories'] %}
            <a href="{{ category|link }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}
        {% endfor %}
    {% endif %}
{% endfor %}
```

This renders as:

```
<a href="/categories/miscellaneous">Miscellaneous</a>
```

My `blogs` content type is defined as follows:

```
blog_posts:
    name: Blog Posts
    singular_name: Blog Post
    slug: blog
    singular_slug: blog
    record_route: blog_post
    fields:
        title:
            type: text
            class: large
            group: content
            label: Title
        content:
            type: article
        slug:
            type: slug
            uses: title
            group: Meta
    taxonomy: [ categories, tags ]
    icon_many: "fa:newspaper"
    icon_one: "fa:newspaper"
```

### Steps to reproduce

* Create a default Bolt install using Composer
* Set up the `blog_posts` content type, as above
* Create a blog post in the `blog_posts` content type and select a category for it
* Add the Twig code to the home page template to render out the categories for each blog post
* Observe the link generated doesn't seem to use `singular_slug`

### Expected result

The `singular_slug` value of `category` is created, like:

```
<a href="/category/miscellaneous">Miscellaneous</a>
```

### Actual result

The `singular_slug` option is ignored, and `slug` is used instead:

```
<a href="/categories/miscellaneous">Miscellaneous</a>
```

You should be able to observe this on [my development site](https://my.andysh.dev/).
