### ISSUE TITLE
Template select field not working correctly when templates in sub dir

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2070]
The template select field does not pick my selected template when the template.twig is stored in a sub directory of my theme folder.

Example:

My theme structure:

themename_folder
- templates_folder
-- mytemplate_01.twig
-- mytemplate_02.twig
theme.yaml

In my theme.yaml:
`template_directory: templates`

My contenttype:
```
pages:
    name: Pages
    singular_name: Page
    fields:
        slug:
            type: slug
            uses: title
            group: content
        title:
            type: text
        body:
            type: html
            height: 300px
            allowtwig: true
        template:
            type: templateselect
            #filter: '*.twig'
    record_template: mytemplate_01.twig
```
If I select `mytemplate_02.twig` in the backend editor it's correctly stored but not rendered. There is no error message available.
It looks like the path is incorrect.

-------

    Install type: Packaged distribution
    Database: mysql 5.7.26 - 127.0.0.1 via TCP/IP
    PHP version: 7.3.9
    Symfony version: v5.1.8
    Operating System: Darwin - 19.6.0
    Assets version: 4.1.4
