### ISSUE TITLE
Editor with imagelist disappears in prod

### ISSUE THREAD

**Issue by izzyu91** [bolt/core#2090]
Seems to be a dev / prod mode bug.

If I want to create a new element of a custom content type the form does not display correctly. The labels are displayed without the form fields and then disappear about a second later.

![image](https://user-images.githubusercontent.com/9365577/97809959-bbf14c00-1c70-11eb-8c64-e03bc8e4274a.png)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.1.0 - 4.1.4
| Install type                                          |  Composer install
| PHP version                                           | 7.3 / 7.4 |
| Web server                                            | Apache / Built-in
| For UX/UI issues                                      | Google Chrome 86.0.4240.111 on macOS

Reproduction
------------

Create a content type containing a field of type `imagelist` and create a new instance.

### Bug summary

The form is not displayed as shown in the screenshot.

### Specifics

- The error does not show when editing an existing element of the same content type.
- There are no javascript errors on the browser JS console in prod mode.
- In dev mode an error is shown

![image](https://user-images.githubusercontent.com/9365577/97810065-7e40f300-1c71-11eb-8cf0-4d7629cec123.png)

- The definiton of the affected content type 

```yaml
objects:
  name: Objekte
  singular_name: Objekt
  slug: objects
  default_status: published
  fields:
    title:
      type: text
      info: 'Dieser Text wird als Titel des Objekts verwendet.'
      group: 'Objekt'
      label: 'Titel'
    slug:
      type: slug
      uses: number
    number:
      type: text
      label: Objektnummer
      info: 'Diese Nummer dient der Referenz und kann von den Kunden genutzt werden, um das richtige Objekt zu identifizieren.'
    stat:
      label: 'Status'
      type: select
      values: ['Aktiv', 'Reserviert', 'Vermietet', 'Verkauft']
      default: 'Aktiv'
      info: 'Dient der Anzeige für die Kunden. Um die Sichtbarkeit eines Objekts zu verändern, bitte Objekt löschen oder Veröffentlichung unter Meta ändern.'
    description:
      label: 'Beschreibung'
      type: textarea
      info: 'Dieses Feld wird dem Besucher nur angezeigt, wenn eine Beschreibung angegeben wurde.'
    images:
      label: 'Bilder'
      group: 'Bilder'
      type: imagelist
```

### Expected result

The form is shown as defined in the content type.
