### ISSUE TITLE
Adding order on fields hides entries when fields are not always present

### ISSUE THREAD

**Issue by jadwigo** [bolt/core#2104]
If you add a content type like 'products' en fill it with some entries. And then add a field `weight` to use as a ordering field on listings the records will be hidden in the back-end and in the front end listing pages.

The products can be seen when another field is used for sorting.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.0 
| Install type                                          |   Composer install
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes/no
| PHP version                                           | 7.4 |
| Web server                                            |  Nginx
| For UX/UI issues                                      | *

Reproduction
------------

Set up a contenttype with something like the following

```
products:
    name: Products
    singular_name: Product
    fields:
        title:
            type: text
            localize: true
            label: Name of this product
        price:
            type: text
            label: Product price
    show_on_dashboard: true
    records_per_page: 20
    listing_records: 8
    viewless: false
    default_status: published
    searchable: true
    order: id
    locales: ['nl', 'en']
```

After you've added some entries and you add a field in the `contenttypes.yaml` to sort the products, like `weight` with a number and a default value.

```
products:
    name: Products
    singular_name: Product
    fields:
        title:
            type: text
            localize: true
            label: Name of this product
        price:
            type: text
            label: Product price
        weight:
            type: number
            label: Ordering on the site
            default: 0
            mode: integer
            variant: inline
            postfix: Higher numbers will be displayed earlier, so number 100 comes before number 40 in the product list
    show_on_dashboard: true
    records_per_page: 20
    listing_records: 8
    viewless: false
    default_status: published
    searchable: true
    order: weight
    locales: ['nl', 'en']
```

The default listing will not show items where the 'weight' field is not set.

### Bug summary

The listing in `vendor/bolt/core/src/Controller/Frontend/ListingController.php` does not select items where the order field is not present
