### ISSUE TITLE
viewless setting doesn't disable list view

### ISSUE THREAD

**Issue by simongroenewolt** [bolt/core#2109]
When you create a content type and set `viewless` to `true` I expect both the 'single' view and the 'listing' view to be unavailable. At the moment the listing view is still registered when you set `viewless` to `true`.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 |  4.0 / 4.1 / master
| Install type                                          |  Composer install
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 7.2 / 7.3 / 7.4 |
| Web server                                            | Apache / Nginx / Built-in, version [ version ]

Reproduction
------------

Create a content type with viewless true

```
promos:
    name: Promos
    singular_name: Promo
    fields:
        heading:
            type: text
        subheading:
            type: textarea
        body:
            type: textarea
    viewless: true
```

If you now visit http://localhost:8088/promos you'll see a list view.
