### ISSUE TITLE
New Feature: add keys setting for select field type

### ISSUE THREAD

**Issue by denis-gorin** [bolt/core#2132]
As it was in Bot3 (updated)

> If you wish to store another field or value from the original ContentType in your database, use the `mode: format` and set the `format` settings . If you do this, it will not store the 'id', but the formatted value of the field(s) you specify. For example:

``` yaml
vendor:
    type: select
    values: vendors/title
    mode: format
    format: '{title} - {sub_title}'
```

This is good in combination with `title_format` in ContentTypes settings for concretize listing elements in dashboard

``` yaml
title_format: '{vendor}: {title}'
```

![image](https://user-images.githubusercontent.com/3963911/99341368-5336e000-28bc-11eb-95bb-12fa9caaef9f.png)
