### ISSUE TITLE
Duplicate URLs for `contenttypes` listing & records

### ISSUE THREAD

**Issue by doup** [bolt/core#2159]
Different URLs show the same content. This is bad for SEO.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.1
| Install type                                          |  Composer install
| <abbr title="Backwards Compatibility">BC</abbr> Break | yes
| PHP version                                           | 7.4 |
| Web server                                            | Built-in
| For UX/UI issues                                      | –

Reproduction
------------

### Bug summary

- Given a `projects` `contenttype`:
    ```yaml
    projects:
        name: Projects
        singular_name: Project
        …
    ```
- Both `/project` & `/projects` show the listing page
- Both `/project/lorem-ipsum` & `/projects/lorem-ipsum` show the record

### Specifics

- Bolt 4.1.4

### Expected result

- Only the plural form should be used as it makes more sense for both the listing & individual records:
  - `/projects`: listing
  - `/projects/lorem-ipsum`: record
- The singular `/project*` form should redirect or error with a 404
- Which one to use could be configurable, although I think it's better to force to plural form. I see four cases:
  - list & record plural
  - list & record singular
  - list plural & record singular (maximum ugliness)
  - do nothing? (same as now)

### Actual result

- Currently it doesn't bother, it always shows the content, either in the singular or plural form

### Workaround

- Usage of plural can be forced by setting the `singular_slug` to the plural form:
    ```yaml
    projects:
        name: Projects
        singular_name: Project
        singular_slug: projects # <<<<<<
    ```
- The downside is that in the record template the record cannot be accessed in the singular form (`project.*`) anymore and the more generic `record` or the (nonsense) plural `projects` must be used.
