### ISSUE TITLE
There is no way to translate `contenttype` URL `slug`

### ISSUE THREAD

**Issue by doup** [bolt/core#2162]
Ideally content-types URL portion should be translated.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.1
| Install type                                          |  Composer install checkout
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 7.4 |
| Web server                                            | Built-in
| For UX/UI issues                                      | –

Reproduction
------------

### Bug summary

- There is no way of translating the slug of the `contenttype`

### Steps to reproduce

- Given a `contenttype`:
    ```
    projects:
        name: Projects
        singular_name: Project
        locales: [ca, es]
    ```

### Actual result

- We get the following URLs, both `contenttype` part are in english:
  - `/ca/projects`
  - `/es/projects`

### Expected result

- We should be able to specify the `contenttype` slug for each language (**note that it doesn't say `projects` anymore**):
  - `/ca/projectes` 
  - `/es/proyectos`

**Comment by Sandrine-D** [comment]
Yes, I have the same issue for the slug and it is a blocking point for me as all my URL already exist with a translated slug in bolt 3.7. So migration is impossible without this.

Another thing: It is impossible to link a slug to a "localize" field and also sort it in backend. 
It is unfortunately a regression since bolt 3.7.

Here an exemple of what I need to do:

```
contenttype:
    name: MyContenttypes
    singular_name: MyContenttype
    fields:
        title:
            type: text
            required: true
            **localize: true** 
        slug:
            type: slug
            uses: title
            **localize: true**
    locales: ['fr', 'en']
    order: **title**
```

Thank you!

**Comment by doup** [comment]
I tried localizing the `slug` and it worked, although you need to set it explicitly for the alternate languages. Just in case, my issue is for the `contenttype` portion, e.g.:
- `/es/destinacion/islandia`

**Comment by Sandrine-D** [comment]
You are right! Stupidly I hadn't tried to put only the slug in `localize:true`, as the `uses` attribute need now to be linked on a no "localize" field.

Regarding the contenttype, unfortunately it is already the case since the beginning. On my side, I found a contenttype name which can be fine in both languages, otherwise I use the routing.yml file to remove the contenttype in the URL.

**Comment by doup** [comment]
In my WIP project I've changed the `routes.yml` to translate the URLs, but I noticed that if you do that then `locales()` helper is useless as it returns weird URLs. I prefer not to go against the CMS, so for now I'm going to translate the `contenttype` name to the main locale (I really don't like this solution, as I like my code to be in english).

The ideal solution would be to be able to define the slug per locale in the `contenttype` definition, something like this:

```yaml
projects:
    # ...
    locales:
        ca: projectes
        es: proyectos
```
