### ISSUE TITLE
`type: checkbox` shouldn't be permanent. ;-)

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#2171]
If we have a contenttype like this: 

```yaml
dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title
        clicky2:
            type: checkbox
    icon_many: “fa:viruses”
    icon_one: “fa:virus”
```

We can then select the checkbox.. save it.. unselect it, and save it again.. The checkbox shouldn't be checked anymore, but it is. 🤦
