### ISSUE TITLE
Markdown editor displays HTML and doesn't recognize markdown anymore

### ISSUE THREAD

**Issue by brennanmurphy** [bolt/core#2190]
I've found that when using the Markdown editor, sometimes the content gets converted to HTML and then the editor doesn't parse Markdown anymore. I've tried to nail down the issue, but I can't always reproduce it. I'm fairly new to Bolt so hopefully this isn't just a configuration issue on my end and apologies in advance if it is. 

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.1.4
| Install type                                          |  Composer install
| PHP version                                           | 7.4.12
| Web server                                            | Apache
| For UX/UI issues                                      | Firefox 83.0

Reproduction
------------

### Bug summary

Intermittently, the markdown editor will convert the entered content into HTML, saving the HTML to the database, and refuse to convert new markdown text into the HTML anymore. 

I am not able to 100% reproduce this error, but usually after a few saves of a post, it will happen. It seems to always occur is the content includes code formatted in the long form code block with a class added, although it does occur in other cases.  

### Steps to reproduce

1. Add the following to contenttypes.yaml:
```
blog:
    name: Blog Posts
    singular_name: Post
    slug: posts
    singular_slug: post
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        body:
            type: markdown
            label: Post Content
    taxonomy: [ tags ]
    record_template: blog-post.twig
    listing_template: blog-list.twig
    listing_records: 10
    default_status: draft
    order: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
```

2. Create a new blog post, include the following in the "Post Content":
~~~
```php
<?php function_name(); ?>
```
~~~

3. Save the post.

### Screenshots
Here is a screenshot of me creating a new post, before saving it:
<img width="1440" alt="Screen Shot 2020-11-28 at 10 49 48" src="https://user-images.githubusercontent.com/13474579/100522791-bf410000-3168-11eb-8318-ed80b36458cc.png">

Here is a screenshot after that post is saved the first time:
<img width="1440" alt="Screen Shot 2020-11-28 at 10 50 26" src="https://user-images.githubusercontent.com/13474579/100522799-d08a0c80-3168-11eb-98bf-b2a911c2de03.png">

Here is a screenshot after I added the class php to the code block, but before I saved it:
<img width="1440" alt="Screen Shot 2020-11-28 at 10 51 08" src="https://user-images.githubusercontent.com/13474579/100522811-e4ce0980-3168-11eb-8121-a4eb7290c5ca.png">

Here is a screenshot after I saved the post with the new php class to the code block:
<img width="1440" alt="Screen Shot 2020-11-28 at 10 51 43" src="https://user-images.githubusercontent.com/13474579/100522816-f3b4bc00-3168-11eb-9e51-2884ad805568.png">

I attempted to debug and solve the issue on my end, but I just don't have enough experience with Vue or Symfony. Will keep trying and I'll post any updates here, but any insight would be much appreciated.
