### ISSUE TITLE
Taxonomy with Number and + converted to int and cannot be added to a content type

### ISSUE THREAD

**Issue by develth** [bolt/core#2201]
I have a taxonmy option called '66+', when adding it at the Backend to the Content-Type, i get an Error:

> Argument 2 passed to Bolt\Repository\TaxonomyRepository::factory() must be of the type string, int given, called in /var/www/bolt/vendor/bolt/core/src/Controller/Backend/ContentEditController.php on line 482

When debugging in Frontend, i recognized that the value is already set as int by vue.

> value='["50-65",66]'

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 4.1.8
| Install type                                          |  Composer install
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 7.4 |
| Web server                                            |  Nginx
| For UX/UI issues                                      | Firefox Developer Edition 84.0b4

Reproduction
------------
Add Taxonmy like 

```
offerAges:
  name: Age-Groups
  singular_name: Age-Group
  slug: ages
  singular_slug: age
  behaves_like: categories
  multiple: true
  options: [ "8-10", "10-14", "14-16", "16-18", "18-20", "20-29", "30-49", "50-65", "66+" ]
  required: true
```

### Steps to reproduce

Add Taxonmy to Content-Type

### Expected result

Should save  '66+', not 66.

### Actual result

Error, because converted to integer
