### ISSUE TITLE
Upgrade 4.0 -> 4.1.8 fails with app_locales setting error

### ISSUE THREAD

**Issue by wgaulke** [bolt/core#2208]
Current version is 4.0 stable. Tried composer update for this version -> fails with exception.

`The <code>e','en']</code> locale was requested, but permitted locales are <code>en, de, nl, es, fr, pl, it, hu, pt_BR, ja, nb, nn, nl_NL, nl_BE, is, ru</code>. Please check your services.yaml app_locales setting.`

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 |  4.0
| Install type                                          |  Composer install
| PHP version                                           | 7.4 |
| Web server                                            | Apache / Nginx 

Reproduction
------------

We tried to update our Bolt 4.0.0 installation to the latest and greatest version. We use a multilang setup (de, en) which is currently running fine. However, after the composer update we got a language related exception:
`
[2020-12-03T09:20:28.351313+00:00] request.CRITICAL: Uncaught PHP Exception Bolt\Exception\ConfigurationException: "The <code>e','en']</code> locale was requested, but permitted locales are <code>en, de, nl, es, fr, pl, it, hu, pt_BR, ja, nb, nn, nl_NL, nl_BE, is, ru</code>. Please check your services.yaml app_locales setting." at /var/www/vhosts/nfc21.de/relaunch2.nfc21.de/nfc21/vendor/bolt/core/src/Configuration/Parser/ContentTypesParser.php line 170 {"exception":"[object] (Bolt\\Exception\\ConfigurationException(code: 0): The <code>e','en']</code> locale was requested, but permitted locales are <code>en, de, nl, es, fr, pl, it, hu, pt_BR, ja, nb, nn, nl_NL, nl_BE, is, ru</code>. Please check your services.yaml app_locales setting. at /var/www/vhosts/nfc21.de/relaunch2.nfc21.de/nfc21/vendor/bolt/core/src/Configuration/Parser/ContentTypesParser.php:170)"} []`

Our services.yaml
```
parameters:
    locale: 'de'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en|de|nl|es|fr|pl|it|hu|pt_BR|ja|nb|nn|nl_NL|nl_BE|is|ru
    app.notifications.email_sender: werner.gaulkenfc21.de
    bolt.table_prefix: bolt_
    bolt.backend_url: /bolt

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'
            $projectDir: '%kernel.project_dir%'
            $publicFolder: '%bolt.public_folder%'
            $tablePrefix: '%bolt.table_prefix%'
```

A content-type example:
```
homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
        slug:
            type: slug
            uses: title
            group: meta
        content:
            type: html
            height: 300px
            localize: true
    viewless: false
    locales: ['de','en']
    singleton: true
```

### Specifics

We changed default locale to 'de', everything else is standard bolt config :)

Looking forward to your input. Loving Bolt4 :)
