### ISSUE TITLE
Localize menu

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2222]
We could localize the menu like so:

```
main:
  - en_label: Home
  - es_label: Incio
    link: homepage
    class: homepage
```

Then make sure that the default twig template that renders it uses something like this:

```
{{ item[app.request.locale ~ '_label'] }}
```

With proper fallbacks if it is missing.

**Comment by wgnahs** [comment]
A nicer approach to do this, would be:

```
main:
    - label:
        nl: Over ons
        en: About us
      link: "#"
```

And then in the twig template:
```
{{ item.label[app.request.locale]|default('-') }}
```
