### ISSUE TITLE
Issue when adding an image in redactor editor

### ISSUE THREAD

**Issue by Sandrine-D** [bolt/core#2260]
Hello,
I have an issue when I add images in Bolt Backend **redactor contenttype** Editor.
Adding a file in File Management is fine.

Details
-------

⚙️  Bolt
========

 Bolt version: 4.1.5
 
 * Install type: Packaged distribution
 * Database: mysql 10.2.36-MariaDB - Localhost via UNIX socket (with JSON)
 * PHP version: 7.4.13
 * Symfony version: v5.1.8
 * Operating System: Linux - 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64

Reproduction
------------

Drop or select file in the dedicated area.
This happens with all my redactor contenttypes, like this:
```
description:
            label: "Article"
            type: redactor
            localize: true
```

### Bug summary

CRITICAL | request | Uncaught PHP Exception ErrorException: "Notice: Undefined index: image" at /home/xxx/vendor/bolt/redactor/src/Controller/Upload.php line 115
-- | -- | --

ErrorException
**in vendor/bolt/redactor/src/Controller/Upload.php (line 115)**
               ` ' $thumbnail = '/thumbs/' . $this->redactorConfig->getConfig()['image']['thumbnail'] . '/'; `

Thanks for your help!

**Comment by bobdenotter** [comment]
I think this is fixed, if you run `composer update`.

**Comment by Sandrine-D** [comment]
Works fine! Thank you :)

**Comment by Sandrine-D** [comment]
@bobdenotter This is very strange, since the upgrade, now all checkboxs have disappeared in contenttype editor. This happens for all contenttypes. 

It is linked to the last release v4.1.9 ?

```
top:
    label: "Afficher sur la page d'accueil?"
    type: checkbox
    default: checked
    group: Options
menu:
    label: "Afficher dans le top menu?"
    type: checkbox
    default: checked
titre_menu:
    label: "Titre top menu"
    type: text
    localize: true
```
<img width="753" alt="Capture d’écran 2020-12-22 à 12 23 32" src="https://user-images.githubusercontent.com/74857683/102883587-b0005a00-4469-11eb-9146-8af131c43bfc.png">
