### ISSUE TITLE
Sortable on relations does not work

### ISSUE THREAD

**Issue by skoop** [bolt/core#2372]
I have created a schema with several content types. One of the contenttypes has a (multi) relation to another content type. I've marked the relation as `sortable: true`. However, the sorting isn't saved correctly in the database.,

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.1.12
| Install type                   |  Composer install with Docker setup
| BC Break                     | no
| PHP version                 | 7.3.26
| Web server                  | Nginx-alpine
| For UX/UI issues        | Firefox 85.0

Reproduction
------------

Content types:

```
tracks:
    name: Tracks
    singular_name: Track
    title_format: "{name}"
    fields:
        name:
            type: text
            class: large
            variant: inline
            fixture_format: '{name}'
        image:
            type: image
        spotify_link:
            type: text
            label: Link
            placeholder: 'Link to spotify song'
            postfix: "Use this to add a link for this Track."
            fixture_format: '{url}'
        youtube_link:
            type: text
            label: Link
            placeholder: 'Link to youtubesong'
            postfix: "Use this to add a link for this Track."
            fixture_format: '{url}'
        slug:
            type: slug
            uses: [ name ]
    relations:
        artists:
            multiple: true
            required: true
            sorted: true
            label: Which artist(s) made this track?
            order: -id

outlaw41s:
    name: Outlaw41s
    singular_name: Outlaw41
    title_format: "{number} ({publish_date})"
    record_template: outlaw41-detail.twig
    order: -number
    fields:
        number:
            type: number
            mode: integer
        publish_date:
            type: date
            mode: date
        slug:
            type: slug
            uses: [ number ]
    relations:
        tracks:
            multiple: true
            sortable: true
            required: false
            label: Which track is on which position?
```

### Bug summary

The order of the relations on a `sortable` relation is not persisted in the database.

### Specifics

I have a whole bunch of tracks added. Now I create an "Outlaw41", and add relations to tracks the new record. The relations are saved in the database, but in random order, instead of the order I have in the multiselect field. The drag & drop behaviour of the relations works fine, but it isn't saved in the correct order. The database table `bolt_relation` has all `0` values in the `position` field.

![Screenshot (121)](https://user-images.githubusercontent.com/90003/107060896-d0953100-67d7-11eb-972f-ba6a042b23b7.png)

### Steps to reproduce

I add a new record including the relations. I drag & drop the relations to the correct order. I save. 

### Expected result

The record now retains the correct order of the relations.

### Actual result

The order of the relations in the record are completely random
