### ISSUE TITLE
Impossible to add content with nested collections

### ISSUE THREAD

**Issue by Cereal2nd** [bolt/core#2402]
Nested collections in content types gives problems in the GUI

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0
| Install type                   | Composer install
| BC Break                     | ????
| PHP version                 | 7.4
| Web server                  | Apache 
| For UX/UI issues        | Firefor 84

### Bug summary

When we create a content type with 2 levels of collections we run into problems in the GUI.
The first collection works like expected, but the nested collection (inside the first one) we can not click the add button, so we can not add such an item.

### Steps to reproduce

create a content type like below and try to add a band and inside the band a video url.

```
event:
    name: Events
    singular_name: Event
    fields:
        naam:
            type: text
            label: Events name
            group: global
            required: true
        image:
            type: image
            group: global
            required: true
        teaser:
            type: redactor
            fixture_format: '{paragraph}'
            group: global
            required: true
        datum:
            type: date
            group: global
            required: true
            mode: datetime
            index: true
        vvk:
            type: number
            group: global
            required: true
            min: 1
            mode: float
        kassa:
            type: number
            group: global
            required: true
            min: 1
            mode: float
        staat:
            type: select
            values: [ none, uitverkoct, geanuleerd, uitgesteld ]
            group: global
            required: true
        bands:
            type: collection
            group: bands
            fields:
                band:
                    type: set
                    fields:
                        naam:
                            type: text
                        stijl:
                            type: text
                        land:
                            type: text
                        image:
                            type: image
                        bio:
                            type: redactor
                        website:
                            type: text
                        facebook:
                            type: text
                        instagram:
                            type: text
                        twitter:
                            type: text
                        youtube:
                            type: text
                        video:
                            type: collection
                            fields:
                                url:
                                    type: embed

```
### Expected result

That it would be possible to expand the second level connection

### Actual result

We can not expand the 2nd level collection, so we can not add video urls

![afbeelding](https://user-images.githubusercontent.com/3715825/108105076-6d838400-708c-11eb-8fad-c65947d44138.png)
