### ISSUE TITLE
Image inside collection does not generate the correct path

### ISSUE THREAD

**Issue by Cereal2nd** [bolt/core#2413]
When you add an image field inside a collection the resulting src attribute in the twig template does not inlcude the files subdir.
Outside of a collection this works

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0
| Install type                   | Composer install
| BC Break                     | yes
| PHP version                 | 7.3
| Web server                  | Apache
| For UX/UI issues        | firefox 84

Reproduction
------------
Create a content type with 2 images fields:
one in the 'main' area, a second one inside a collections field
when using the showImage() function in the twig templates the result is different:

for the 'main' image field:
src = /files/contenttype/year/month/file

for the image field inside the collection:
src = contenttype/year/month/file

**Comment by bobdenotter** [comment]
Hi, 

Which version is this exactly? 

Could you paste the relevant Contenttype and Twig as well?

**Comment by Cereal2nd** [comment]
"bolt/core": "^4.1",


twig:

band.image:showimage()

contentype:
```
event:
    name: Events
    singular_name: Event
    fields:
        naam:
            type: text
            label: Events name
            group: global
            required: true
        image:
            type: image
            group: global
            required: true
        bands:
            type: collection
            group: bands
            fields:
                band:
                    type: set
                    fields:
                        naam:
                            type: text
                        image:
                            type: image
```
