### ISSUE TITLE
|excerpt filter always shows in the default locale when an excerpt_format is set for a contenttype

### ISSUE THREAD

**Issue by M-Stgelais** [bolt/core#2474]
When I set an `excerpt_format` with specific fields in a `contenttype`, whenever I use the filter `|excerpt` in a template, no matter what the current `locale` is, it will always show the excerpt text in the default locale

### Details
Relevant Bolt Version : 4.1.15
Install type: Composer install
PHP version: 7.3
Web server: Apache
Database: MySQL

### Reproduction
For example, this contenttype:
```

expos:
    name: Expositions et activités
    singular_name: Exposition ou Activité
    show_in_menu: Expositions et Activités
    fields:
        texte:
            type: redactor
            localize: true
        other_fields:
            [...]
    taxonomy: [ expo_categories ]
    viewless: false
    viewless_listing: true
    record_template: exposition-detail.twig
    excerpt_format: "{texte}"
    default_status: published
    order: -publishedAt
    records_per_page: 50
    icon_many: "fa:camera"
    icon_one: "fa:camera"
    locales: ['fr', 'en']

```

I set the `excerpt_format` to `"{texte}"`, to make sure the excerpt of the record is made from the `texte` field. The field has content for the `fr` locale and also has content for the  `en` locale.

Now on my page, even if the `current locale` is set to `en`, `record|excerpt` will always show the content in my default locale, which is `fr`.

### My code in my template file:
![image](https://user-images.githubusercontent.com/78932889/111491075-efa9ab80-8711-11eb-9c41-e92cf1a37a8f.png)

### The result:
![image](https://user-images.githubusercontent.com/78932889/111492006-b32a7f80-8712-11eb-8223-b814d66f2c93.png)

This is especially problematic in the global search. The results shown can be from different contenttypes, none of them has the same `excerpt_format`, so there is no work around.

Am I doing something wrong? Please tell me if I'm not clear of if you need more information.

Thank you!
