### ISSUE TITLE
Select field values format does not allow "/"

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2503]
Hi everyone!

I've noticed that when formatting the values of a Select field it does not allow to use the slash (/) to format the values of the select list.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 5.0 beta 3
| Install type                   |  Composer install 
| BC Break                     | yes/no
| PHP version                 | 7.2 / 7.3 / 7.4 |
| Web server                  | Symfony local server

Reproduction
------------

- Add the following Select field configuration:

```
book:
            label: Book
            type: select
            values: books/{id} / {title}
            keys: id
            autocomplete: true
            sort: -id
            class: narrow
            variant: inline
            required: true
```

- Check that only the id is displayed in the list of select values. What comes after the id ( / {title}) seems to be missing

### Expected result

Select values with / in the format pattern, which would give values like "35 / The mist" for example.

### Actual result

Although this is not breaking the edit page in the CMS, the values are being displayed like "35 " for example, missing part of the format,.
