### ISSUE TITLE
Reverse relation remove on content save

### ISSUE THREAD

**Issue by napley** [bolt/core#2504]
Reverse relation remove on content save

Details
-------

Install type: Packaged distribution
Database: mysql 5.5.62 - service.mysql via TCP/IP
PHP version: 7.4.11
Symfony version: v5.2.6
Operating System: Linux - 5.4.0-70-generic
Assets version: 4.1.16

Reproduction
------------
On a contentA I define a relation:
```
contentA:
    //...
    relations:
        contentB:
            label: contentB
            required: false
            multiple: false
```

On a contentB I define a relation:
```
contentB:
    //...
    relations:
        contentC:
            label: contentC
            required: false
            multiple: false
```

When I save contentA with a contentB selected I see the relation in database.
After I save the contentB without or with a contentC selected, the relation between contentA and contentB is removed.

I see in the contentEditController, all the relation is removed before insert new:
```
//...
 private function updateRelation(Content $content, $newRelations): void
    {
        $newRelations = (new Collection(Json::findArray($newRelations)))->filter();
        $currentRelations = $this->relationRepository->findRelations($content, null, true, null, false);

        // Remove old ones
        foreach ($currentRelations as $currentRelation) {
            $this->em->remove($currentRelation);
        }
       //...
```
I understand why relation is removed but I don't understand why reverse relation are removed too. 
So I made a fix which change the bidirectionnal attribute:
`        $currentRelations = $this->relationRepository->findRelations($content, null, false, null, false);`

Do you think there will be side effect ?

The commit in my repo with the modification : https://github.com/napley/core/commit/35c7a6e3150a5ba084a3bc1b7b421f711d454f0c
