### ISSUE TITLE
Relation format which contains `&` is show as `&amp;`

### ISSUE THREAD

**Issue by I-Valchev** [bolt/core#2513]
This should not be escaped, it should shown `Test & Test`, not `Test &amp; Test`

Eg:

```yaml
    relations:
        books:
            format: "{title}"
```
