### ISSUE TITLE
Unable to change date field in collection/set [updated]

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2588]
UPDATE
**I did some more tests with this. It looks like it's just not possible to use a type:** `datetime field `**in a set.**

I tried to change a `text` field to a `date` field and later on to a `datetime` field in a collection set but Bolt does not change the field type in the backend.

To reproduce the bug (?), I did this:

Create a contenttype with a collection field containing a set
Create a field type: text, i.e.

```
item_datetime:
    type: text
    label: Starttijd
    variant: inline
```
Create a record in this contentype. This was the moment I thought _"I need a date field here..."_
Go back to the contenttypes.yaml and change the field type:
```
item_datetime:
    type: date
    label: Starttijd
    variant: inline
```

Create a record again in this contentype:  _"Oh, I need time too!"_
Go back to the contenttypes.yaml and change the field type:
```
item_datetime:
    type: datetime
    label: Starttijd
    variant: inline
```

Bolt does not change my field to a datetime selector.

My contenttype now:

```
programma:
    name: programma
    singular_name: Programmaitem
    fields:
        title:
            type: text
            class: large
            label: Titel
        programmaitems:
            type: collection
            collapsible: true
            fields:
                item:
                    type: set
                    fields:
                        item_title:
                            type: text
                            class: narrow
                            variant: inline
                            label: Titel
                        item_datetime:
                            type: datetime #this was a text field at first. Changed it to date later and to datetime after that
                            label: Starttijd
                            variant: inline
                        item_length:
                            type: number
                            mode: integer
                            label: Duur
                            variant: inline
                        item_link:
                            type: text
                            variant: inline
                            label: URL
                        item_body:
                            type: text
                            label: subtekstje
                            variant: inline

```

---
Bolt 4.1.19
