### ISSUE TITLE
Not able to empty imagelist field

### ISSUE THREAD

**Issue by peterboorsma** [bolt/core#2606]
If you have a record with an imagefield it's not possible to empty the list of images. Frontend returns placeholder.png image.

My contenttype field:
```
        gallery:
            type: imagelist
            label: Slideshow
            alt: true
            extensions: [ gif, jpg, png ]
```
My template:
```
{% if record.gallery is defined and record.gallery|length > 0 %}
{% for image in record.gallery %}
    <img src="{{ thumbnail(image, 600, 400, fit='c') }}">
{% endfor %}
{% endif %}
```

1. I add an image to the imagelist in the backend by clicking "Add new image" in the imagelist field.
2. Oh, I don't need an imagelist here > Click "Remove"
3. Save my record
4. Open the record in a browser, the placeholder.png shows up

I'm unable to completely empty my imagefield

-------
 Bolt 5.0.0 beta 7 - Nothing to see here!

System Information:

    Install type: Packaged distribution
    Database: mysql 5.7.32 - 127.0.0.1 via TCP/IP
    PHP version: 7.4.15
    Symfony version: v5.3.0
    Operating System: Darwin - 20.5.0
    Assets version: 4.99.7
