### ISSUE TITLE
After upgrade to Bolt 4.2, admin sidebar doesn't show up

### ISSUE THREAD

**Issue by Deuchnord** [bolt/core#2771]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.2
| Install type                   |  Composer install
| BC Break                     | probably
| PHP version                 | 7.4
| Web server                  | Nginx
| For UX/UI issues        | Firefox 90, Chromium 92

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I'm migrating from Bolt 4.1.13 to Bolt 4.2.1 and since then, I can't see the admin sidebar menu anymore.

### Specifics

- URL impacted: `/bolt/` and all the URLs in the inside
- Bolt version: 4.2.1, upgraded from 4.1.13 with Composer

### Screenshots

![Screenshot showing the sidebar being empty](https://user-images.githubusercontent.com/7600265/129364693-380390bd-bb3c-4710-a37d-48cacfe86b65.png)

Noticed that the DOM contained a weird tag instead of actual HTML content:

![DOM content](https://user-images.githubusercontent.com/7600265/129365360-66371dc8-9e38-4a14-85ed-4dee85718275.png)

### Steps to reproduce

- Add a content type in `config/bolt/contenttypes.yaml`:
  ```yaml
  content:
    name: Contents
    singular_name: Content
    fields:
        title:
            type: text
            label: Title
            required: true
        text:
            type: text
            label: Textual content
            required: true
   ```
- Open admin page: the sidebar remains empty.

Note that new contents can still be created by visiting `/bolt/new/content`.

### Expected result

A menu should be displayed in the sidebar.
