### ISSUE TITLE
{{ setcontent }} with where clause on a select field does not fetch records

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2806]
Hi all!

It seems that `setcontent` is not working when trying to fetch records using the where clause on a select field.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0
| Install type                                          | Composer
| PHP version                                           | 7.3
| Web server                                            | Symfony Local server

Reproduction
------------

Given the following Contenttype configuration:
```
wikipaginas:
    name: Wiki Paginas
    singular_name: Wiki Pagina
    slug: wikipaginas
    singular_slug: wikipagina
    fields:
        project:
            type: select
            values: projecten/{projectnummer},{title}
            keys: id
            autocomplete: true
            sort: -projectnummer
            class: narrow
            variant: inline
            postfix: <br><hr>
            searchable: true
```
and trying to fetch records like `{% setcontent wikipaginas = 'wikipaginas' where { project : record.id } %}` does not return anything.

### Expected result

Fetch existing records which match this query

### Actual result

No record are fetched even though there are matches in the database
