### ISSUE TITLE
Array to string conversion error when using printquery in {{ setcontent }}

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2807]
Hi all,

This issue popped up when trying to figure out what was going on with #2806 
Using the printquery option in the setcontent statement seems to be throwing some errors. See screenshots:

![capture 1](https://user-images.githubusercontent.com/6607455/131327369-8af6064d-c979-486d-ba72-14f4ad8fb31f.PNG)
![capture 2](https://user-images.githubusercontent.com/6607455/131327266-3f2e77b1-9f2b-43f5-8b12-92b9da736c66.PNG)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0
| Install type                                          |  Composer
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server

Reproduction
------------

Given the following Contenttype configuration:
```
wikipaginas:
    name: Wiki Paginas
    singular_name: Wiki Pagina
    slug: wikipaginas
    singular_slug: wikipagina
    fields:
        project:
            type: select
            values: projecten/{projectnummer},{title}
            keys: id
            autocomplete: true
            sort: -projectnummer
            class: narrow
            variant: inline
            postfix: <br><hr>
            searchable: true
```

and trying to print the following query `{% setcontent wikipaginas = 'wikipaginas' where { project : "[" ~ record.id ~ "]" } printquery %}` makes the page break

### Expected result

Page doesn't break and I can see the printquery content

### Actual result

Page breaks and I don't see the page query content
