### ISSUE TITLE
Relations to a localized contenttype field do not show up in the back-end

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/core#2930]
Relations to a **localized** contenttype field do not show up in the back-end

```
relations:
    tentoonstellingen:
        multiple: false
        order: title
        label: Hoort bij een tentoonstelling?
```

If the contenttype field is localized it is not possible to select the item from the dropdown selection in the backend

![Capture_relations_empty](https://user-images.githubusercontent.com/66225295/141456024-a4162758-7a6c-48d5-af8b-917a9ba57536.PNG)

If the contentype field is **not** localized

```
tentoonstellingen:
    name: Tentoonstellingen
    singular_name: Tentoonstelling
    fields:
        title:
            type: text
            class: large
            group: content
            # localize: true
```

the relation shows up in the list

![Capture_relations_working](https://user-images.githubusercontent.com/66225295/141465707-1e1e7dfb-5874-4f82-9e06-66b43b3d6181.PNG)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| PHP version                                           | 7.3
| Web server                                            | symfony CLI
| Database                                      | Distrib 10.3.31-MariaDB
