### ISSUE TITLE
Redactor field toolbar overlaps select list

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2945]
In the frontend of the backend, when placing a Redactor field after a select field the toolbar of the Redactor field overlaps the the select field when it is expanded.

![toolbar_overlapped](https://user-images.githubusercontent.com/6607455/142386943-0e910bc4-ce87-4498-a1ba-d40aa4e2a3b1.PNG)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.3
| Install type                                          |  Composer install 
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server

Reproduction
------------
Add a select field before a redactor field like:
```
contacts:
    type: select
    label: Contacts
    values: ['Contact 1','Contact 2','Contact 3','Contact 4','Contact 5','Contact 6','Contact 7']
body:
    type: redactor
    label: "Body"
```

Expand the select box to select a value.

### Expected result

The entire list of values in the select box is visible

### Actual result

Not all the values in the select list are visible because the redactor's field toolbar overlaps the list
