### ISSUE TITLE
In routes.yaml contentlisting route sample breaks

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2948]
Using this sample route found in `routes.yaml` breaks:

```
contentlisting:
    path: /{contenttypeslug}
    defaults:
        _controller: Bolt\Controller\Frontend\ListingController::listing
    requirements:
        contenttypeslug: '%bolt.requirement.pluralcontenttypes%'
```

![Capture](https://user-images.githubusercontent.com/6607455/142605062-2a20b708-5f0d-41ad-acf4-86234a86d085.PNG)

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.3
| Install type                                          |  Composer install
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server
