### ISSUE TITLE
Values in a field with type select only sortable if autocomplete: false

### ISSUE THREAD

**Issue by mcdennem** [bolt/core#2962]
In the Bolt docs [(https://docs.boltcms.io/5.0/fields/select#making-the-selected-values-sortable),](url) the way to make values in a select sortable is described as:

```     
somevalue:
     type: select
     values: programme/{title}
     sort: name
     autocomplete: true
     limit: 1000
```

But with `autocomplete: true` that doesn't work. You have to set `autocomplete: false` to drag and drop the values in the CMS:

<img width="676" alt="Schermafbeelding 2021-11-23 104214" src="https://user-images.githubusercontent.com/49211363/143001673-96bd04a6-8808-472a-a472-6b06a0590b28.png">

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.06
| Install type                                          | Composer install
| PHP version                                           |  7.3  |
| Web server                                            | Built-in, version (Symfony) ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

I created an select type field as described in [https://docs.boltcms.io/5.0/fields/select#making-the-selected-values-sortable](url)

```
 portfolio:
    type: select
    label: Portfolio Items
    values: portfolio/{id},{title}
    multiple: true
    autocomplete: true
    sortable: true
    localize: true
```

### Expected result

I expect the select values to be sortable as drag and drop.

### Actual result

I was not able to sort the values in the select by drag and drop.
