### ISSUE TITLE
It is not possible to add custom class to Select field

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2975]
Having a Select field defined like it follows, won't add the class `number-attribution-group` to the field.

```
selectfield:
    type: select
    values: [ foo, bar, baz ]
    class: number-attribution-group
```

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| Install type                                          |  Composer install 
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server

Reproduction
------------

Add a custom class to a select field like for example:
```
selectfield:
    type: select
    values: [ foo, bar, baz ]
    class: number-attribution-group
```

### Expected result

The custom class is added to the select field.

### Actual result

The custom class is **not** added to the select field.
