### ISSUE TITLE
Prefix and postfix text options are not visible on relationships and taxonomies

### ISSUE THREAD

**Issue by nestordedios** [bolt/core#2989]
Having a taxonomy definition like it's shown below does not add the `prefix` or `postfix` text to the taxonomy input field.
```
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    prefix: "My prefix text"
    postfix: "My postfix text"
    allow_spaces: false
    required: false
```

Having a relation definition like it's shown below does not add the `prefix` or `postfix` text to the taxonomy input field.

```
relations:
        entries:
            prefix: "My prefix text"
            multiple: false
            label: "Choose an entry"
            order: -id
            format: "{title} (№ {id}, {status})"
            postfix: "My postfix text"
```

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| Install type                                          | Composer install
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server

Reproduction
------------

Add the mentioned definitions to the contenttype.yaml and taxonomy.yaml

### Expected result

The prefix and postfix text is displayed on the related input field

### Actual result

The prefix and postfix text is **not** displayed on the related input field.
