### ISSUE TITLE
Fetching records based on select field value gives no results

### ISSUE THREAD

**Issue by SanderOnline** [bolt/core#3063]
When fetching records based on the ID of select field from another contenttype it gives 0 results

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.0
| Install type                                          |  Composer install
| PHP version                                           | 7.2
| Web server                                            | Apache

Reproduction
------------

2 contenttypes were used for this:

Contenttype to define different categories:

```
support:
    name: Support Categories
    slug: support
    singular_name: Support
    singular_slug: support
    fields:
        title:
            type: text
            class: large
            group: content
            label: Support category name
        teaser:
            type: html
            height: 150px
            label: Short text below the title                                            
        slug:
            type: slug
            uses: title
            group: Meta         
    recordsperpage: 100
    default_status: published

```

Contenttype for the different articles:

```
articles:
    name: Articles
    slug: articles
    singular_name: Article
    singular_slug: article
    fields:
        title:
            type: text
            class: large
            label: Page title
            group: content
        subtitle:
            type: text
            label: Subtitle below the title, optional
        teaser:
            type: redactor
            label: Introtext below the subtitle, optional
        supportcategory:
            type: select
            values: support/{title}
            sort: title
            autocomplete: true
            label: Support category
        slug:
            type: slug
            uses: title
            group: Meta
    order: title
    records_per_page : 50
    default_status: published
```

Having the following logic:
- There is a support listing page with all the categories shown
- The support record shows all the articles linked to this specific support page through the "supportcategory" field

### Bug summary

When trying to fetch all the articles with a specific "supportcategory" id it gives 0 results when using either
`{% setcontent articles = "articles" where { 'supportcategory': 36 } %}`
or 
`{% setcontent articles = "articles" where { 'supportcategory': record.id } %}`

When printing the query it shows:
```
SELECT content FROM Bolt\Entity\Content content LEFT JOIN content.fields fields_supportcategory LEFT JOIN fields_supportcategory.translations translations_supportcategory WHERE content.contentType = :ct0 AND ((JSON_SEARCH(translations_supportcategory.value, 'one', :supportcategory_1) != '' AND fields_supportcategory.parent IS NULL AND fields_supportcategory.name = :field_supportcategory) AND content.status = :status_1) ORDER BY content.publishedAt DESC

ct0: "articles"
supportcategory_1: 36
status_1: "published"
field_supportcategory: "supportcategory"
```

An example that does work and gives results:
`{% setcontent articles = 'articles' where { title: 'Test title goes here' } %}`

With the query:
```
SELECT content FROM Bolt\Entity\Content content LEFT JOIN content.fields fields_title LEFT JOIN fields_title.translations translations_title WHERE content.contentType = :ct0 AND ((JSON_EXTRACT(translations_title.value, '$[0]') = :title_1 AND fields_title.parent IS NULL AND fields_title.name = :field_title) AND content.status = :status_1) ORDER BY content.publishedAt DESC

ct0: "articles"
title_1: "Test title goes here"
status_1: "published"
field_title: "title"
```

Hope this helps in explaining the issue i am having.
