### ISSUE TITLE
Canonical link does not correspond with binding in routes.yaml

### ISSUE THREAD

**Issue by evertalbers** [bolt/core#3089]
In routes.yaml  I use
```
entrybinding:
  path: /{slugOrId}
  methods: [GET|POST]
  defaults:
    contentTypeSlug: entry
    _controller: Bolt\Controller\Frontend\DetailController::record
```
so the entries have a nice ’n short URL without `/entry`
but in the source HTML on the frontend I do see `/entry/`  in the URL
```
<link rel="canonical" href="https://mysite.nl/entry/entryname">
<meta name="generator" content="Bolt">
```
And I see the same thing happening in `/sitemap.xml`

Bolt 5.1.2

FYI somebody familiar with Bolt added _"nah, i see it happening on a local setup too"_ in the Bolt slack.
