### ISSUE TITLE
"default" value is ignored for fields defined inside a "set" or a "collection"

### ISSUE THREAD

**Issue by dadaxr** [bolt/core#3113]
### Bug summary

Many Content type fields can have a default value, specified via the "default" option. (see : [docs](https://docs.boltcms.io/5.0/fields/common#default-values))

But this does not work when fields are defined inside a "set" or a "collection" fields

Reproduction
------------
example of a "buggy" content type definition 
```
projects:
    name: Projects
    singular_name: Project
    fields:
        test_text:
            type: text
            default: "default val" #this is working
        test_set:
            type: set
            fields:
                set_text:
                    type: text
                    default: "default val" #this is not working
        test_collection:
            type: collection
            fields:
                collection_text:
                    type: text
                    default: "default val" #this is not working
  ```

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.1.3
| Install type                                          |  Composer install
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 8.1
| Web server                                            | Apache
