### ISSUE TITLE
Cache throws exception when using multiple contenttypes in a `type:select` 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#3114]
When having 

```yaml
caching:
    …
    selectoptions: 3600
    … 
```

Throws an exception, if you're using a select like 

```yaml
somevalue:
    type: select
    values: (events,news,pages)/{title} - {contenttype} № {id} ({status})
```
