### ISSUE TITLE
Multiple table prefixes - Version constructor argument

### ISSUE THREAD

**Issue by matesko** [bolt/core#3123]
When using multiple entity managers and database connections Bolt\Doctrine\Versions throws error

 Argument #2 ($tablePrefix) must be of type string, array given

Bolt Version 5.1.4

To reproduce:

.env
```
DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/bolt.sqlite
DATABASE_URL2=sqlite:///%kernel.project_dir%/var/data/bolt2.sqlite

```

doctrine.yaml
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL)%'
            d2:
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL2)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Bolt:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/vendor/bolt/core/src/Entity'
                        prefix: 'Bolt\Entity'
                        alias: Bolt
                dql:
                    string_functions:
                        JSON_EXTRACT: Bolt\Doctrine\Functions\JsonExtract
                        JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
                        JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                        CAST: Bolt\Doctrine\Query\Cast
                    numeric_functions:
                        RAND: Bolt\Doctrine\Functions\Rand
            d2:
                connection: d2
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
```

services.yaml

```
    app.table_prefix:
        default: bolt_
        d2: foo_
...
       bind:              
            $tablePrefix: '%app.table_prefix%'

```
