### ISSUE TITLE
Absence of mode: integer within set within collection 

### ISSUE THREAD

**Issue by evertalbers** [bolt/core#3183]
I notice that when using a number field within a set inside within a collection, the fields in that set disappear in the backend when not using `mode: integer`.
As soon as I decomment the last line within the code below, everything works fine.
```
                mapset:
                    type: set
                    label: Map iFrame
                    icon: "fas fa-map"
                    fields:
                        textblockheader:
                            type: text
                        mapurl:
                            type: text
                        textafter:
                            type: text
                        height:
                            label: 'Height (% of viewport height)'
                            prefix: 'Value between 1 and 100 (if empty, a value of 50 will be used)'
                            type: number
                            # mode: integer
```
So `# mode: integer`
![Screenshot 2022-04-19 at 20-55-47 European Hydrogen Backbone Maps](https://user-images.githubusercontent.com/3974120/164077100-012be805-3a48-4adc-8398-0edc1f23cbc7.png)
and `mode: integer`
![Screenshot 2022-04-19 at 20-54-37 European Hydrogen Backbone Maps](https://user-images.githubusercontent.com/3974120/164077140-b02dfc69-5b58-442a-a6e1-deb4128d990d.png)

**Good to know**: While I was at it I also tried the same set on its own, so _not_ within a collection, and then the presence/absence of `mode: integer` made no difference.

Bolt 5.1.5, local setup.
