### ISSUE TITLE
[RFC] Allow multiple relations to the same content type

### ISSUE THREAD

**Issue by sxsws** [bolt/core#3192]
Currently, relations are added to a content type by their slug / content_type name. This only allows one content type of relation to be created from a content type. By changing the definition of relations will allow multiple relations to the same content type. This is important because relations are a proper reference to a item of a content type, rather than defining it in an array in one field that a select does, thus making it more searchable and faster.

This is a big limitation to bolt.

I'd like to suggest that relations are defined by a name of the relation, rather than the name of the content type:

```
relations:
    upsell_products:
        content_type: products
        label: "Related Products"
        ... rest of relation code...
    crosssell_products:
        content_type: products
        label: "Cross Sell Products"
        ... rest of relation code...
```

How can you help?
-------------------------------

I could probably code this myself. Not a newbie to symfony development
