### ISSUE TITLE
[FR] Add ability to save uploads in a custom contenttype folder

### ISSUE THREAD

**Issue by eduardomart** [bolt/core#322]
Currently everything is saved to the 'uploads' folder and inside a 'upload date' folder. This just makes files really difficult to find, as you'd have to remember when you uploaded a file to find it.

See this 3.x extension:
https://github.com/blockmurder/bolt-custom-upload-path

This is one of my default extensions to install, but it'd be nice to not have to depend on extensions for something like this.

**Comment by bobdenotter** [comment]
In v4 you can give it a simple string, like this: 

```
    type:
        image:
            type: image
            upload: entries
```

Would that suffice?
