### ISSUE TITLE
Localization bug - When any one field in a set is localized this causes image 'widget' to no longer display the image

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/core#3347]
Hi there,

Take the following set:

![Capture_set_example](https://user-images.githubusercontent.com/66225295/199754824-fc0aa3ad-9e45-41ff-bcb7-4cbfcdaa2da1.PNG)

The set in the contenttypes.yaml (contenttype `pages`) looks like this:

```yaml
testset:
  type: set
  label: TestSet
  fields:
    title:
      type: text
      label: Textveld
      # localize: true
    image:
      type: image
      label: Afbeelding
```

The contenttype in this case also has two locales like so `locales: ['nl', 'en']`

Let say we want to localize only the text field.

This results in the disappearance of the image in the non-default locale, even though the image field is **not** localized!

![Capture_set_image_field_gone](https://user-images.githubusercontent.com/66225295/199759029-e0ed4afc-411e-4863-9d78-fc5cce209a79.PNG)

One would expect the image to be there in the other locale, as the field is **not** localized.

| Relevant Bolt Version                                 | 5.1.18
| Install type                                          |  Composer install
| PHP version                                           | 7.4
| Web server                                            | Symfony
