### ISSUE TITLE
Collection field containing a hidden field breaks the edit form

### ISSUE THREAD

**Issue by doenietzomoeilijk** [bolt/core#3443]
As mentioned in Slack:

I have a contenttype with a Collection-type field `contentblocks`, containing a Set field `publicationssection`, which contains a hidden field.

The full name of that field (which is determined to be collections[contentblocks][publicationssection][2][publications]`, for example), gets overwritten right at the top of `templates/_partials/fields/hidden.html.twig`, to be `fields[publications]` (in this example). This means that I can't store this content item, because _of course_ publications isn't actually a field...

The template for hidden fields seems to deviate from the other field templates in doing its own thing and not extending the base template, because it doesn't want all the html stuff around it, which makes sense. It just shouldn't blindly overwrite the name.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | latest beta
| Install type                                          | composer
| <abbr title="Backwards Compatibility">BC</abbr> Break | no
| PHP version                                           | 8.1
| Web server                                            | Nginx

Reproduction
------------

Example contenttype (the hidden field being inside a set field or not doesn't actually matter for this example):

```yaml
pages:
  # ...
  fields:
    contentblocks:
      type: collection
      fields:
        publicationssection:
          type: set
          fields:
            publications:
              type: hidden
  # ...
```

Now create a record, add a publicationssection to you contentblock, attemt to store the record. You'll get an error stating "Content type `pages` doesn't have field `publications`."
